<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">


<title>DOCTR - Bayesian Statistics</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
/* CSS for syntax highlighting */
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
  }
pre.numberSource { margin-left: 3em;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
/* CSS for citations */
div.csl-bib-body { }
div.csl-entry {
  clear: both;
  margin-bottom: 0em;
}
.hanging-indent div.csl-entry {
  margin-left:2em;
  text-indent:-2em;
}
div.csl-left-margin {
  min-width:2em;
  float:left;
}
div.csl-right-inline {
  margin-left:2em;
  padding-left:1em;
}
div.csl-indent {
  margin-left: 2em;
}</style>


<script src="../site_libs/quarto-nav/quarto-nav.js"></script>
<script src="../site_libs/quarto-nav/headroom.min.js"></script>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-search/autocomplete.umd.js"></script>
<script src="../site_libs/quarto-search/fuse.min.js"></script>
<script src="../site_libs/quarto-search/quarto-search.js"></script>
<meta name="quarto:offset" content="../">
<script src="../site_libs/quarto-html/quarto.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<script src="../site_libs/quarto-html/anchor.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-dark.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="../site_libs/bootstrap/bootstrap.min.js"></script>
<link href="../site_libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="../site_libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="dark">
<script id="quarto-search-options" type="application/json">{
  "location": "navbar",
  "copy-button": false,
  "collapse-after": 3,
  "panel-placement": "end",
  "type": "overlay",
  "limit": 50,
  "keyboard-shortcut": [
    "f",
    "/",
    "s"
  ],
  "show-item-context": false,
  "language": {
    "search-no-results-text": "No results",
    "search-matching-documents-text": "matching documents",
    "search-copy-link-title": "Copy link to search",
    "search-hide-matches-text": "Hide additional matches",
    "search-more-match-text": "more match in this document",
    "search-more-matches-text": "more matches in this document",
    "search-clear-button-title": "Clear",
    "search-text-placeholder": "",
    "search-detached-cancel-button-title": "Cancel",
    "search-submit-button-title": "Submit",
    "search-label": "Search"
  }
}</script>

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>

<link rel="stylesheet" href="../css/mastemr.css">
</head>

<body class="nav-sidebar docked nav-fixed">

<div id="quarto-search-results"></div>
  <header id="quarto-header" class="headroom fixed-top">
    <nav class="navbar navbar-expand-lg " data-bs-theme="dark">
      <div class="navbar-container container-fluid">
      <div class="navbar-brand-container mx-auto">
    <a href="index.qmd" class="navbar-brand navbar-brand-logo">
    <img src="../images/KCL_logo.png" alt="" class="navbar-logo">
    </a>
    <a class="navbar-brand" href="index.qmd">
    <span class="navbar-title">DOCTR</span>
    </a>
  </div>
        <div class="quarto-navbar-tools tools-end">
</div>
          <div id="quarto-search" class="" title="Search"></div>
      </div> <!-- /container-fluid -->
    </nav>
  <nav class="quarto-secondary-nav">
    <div class="container-fluid d-flex">
      <button type="button" class="quarto-btn-toggle btn" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">
        <i class="bi bi-layout-text-sidebar-reverse"></i>
      </button>
        <nav class="quarto-page-breadcrumbs" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/06-1-SEM.html">SEM and Bayesian</a></li><li class="breadcrumb-item"><a href="../chapters/06-2-Bayesian.html">Bayesian Statistics</a></li></ol></nav>
        <a class="flex-grow-1" role="button" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item" aria-controls="quarto-sidebar" aria-expanded="false" aria-label="Toggle sidebar navigation" onclick="if (window.quartoToggleHeadroom) { window.quartoToggleHeadroom(); }">      
        </a>
      <button type="button" class="btn quarto-search-button" aria-label="" onclick="window.quartoOpenSearch();">
        <i class="bi bi-search"></i>
      </button>
    </div>
  </nav>
</header>
<!-- content -->
<div id="quarto-content" class="quarto-container page-columns page-rows-contents page-layout-article page-navbar">
<!-- sidebar -->
  <nav id="quarto-sidebar" class="sidebar collapse collapse-horizontal quarto-sidebar-collapse-item sidebar-navigation docked overflow-auto">
        <div class="mt-2 flex-shrink-0 align-items-center">
        <div class="sidebar-search">
        <div id="quarto-search" class="" title="Search"></div>
        </div>
        </div>
    <div class="sidebar-menu-container"> 
    <ul class="list-unstyled mt-1">
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../index.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Home</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true">
 <span class="menu-text">Introduction to R</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-1" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-1" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-1-Loading_R.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Introduction to R</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/01-2-Intro_tidyverse.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Loading packages and exploring data</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true">
 <span class="menu-text">Introduction to Stats</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-2" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-2" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-1-Descriptive.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Descriptive Statistics</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-2-ChisqPISA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Hypothesis testing and Chi-square tests</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/03-3-T-testsPISA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">T-tests</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/04-Intro_to_graphs.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Making graphs</span></a>
  </div>
</li>
        <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/05-Correlation_and_regression.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Correlation and regression</span></a>
  </div>
</li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true">
 <span class="menu-text">SEM and Bayesian</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-3" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-3" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-1-SEM.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">SEM</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/06-2-Bayesian.html" class="sidebar-item-text sidebar-link active">
 <span class="menu-text">Bayesian Statistics</span></a>
  </div>
</li>
      </ul>
  </li>
        <li class="sidebar-item sidebar-item-section">
      <div class="sidebar-item-container"> 
            <a class="sidebar-item-text sidebar-link text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true">
 <span class="menu-text">Appendices</span></a>
          <a class="sidebar-item-toggle text-start" data-bs-toggle="collapse" data-bs-target="#quarto-sidebar-section-4" aria-expanded="true" aria-label="Toggle section">
            <i class="bi bi-chevron-right ms-2"></i>
          </a> 
      </div>
      <ul id="quarto-sidebar-section-4" class="collapse list-unstyled sidebar-section depth1 show">  
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A1-PISA_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">PISA</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A2-DfE_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">DfE England</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A3-TIMSS_analysis.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">TIMSS, PIRLS and ICILS</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A4-Other_datasets.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Other datasets</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A5-Self_Study_Tasks.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Self Study Tasks</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A6-selecting_statistical_tools.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Selecting statistical tools</span></a>
  </div>
</li>
          <li class="sidebar-item">
  <div class="sidebar-item-container"> 
  <a href="../chapters/A7-QandA.html" class="sidebar-item-text sidebar-link">
 <span class="menu-text">Questions and Answers</span></a>
  </div>
</li>
      </ul>
  </li>
    </ul>
    </div>
</nav>
<div id="quarto-sidebar-glass" class="quarto-sidebar-collapse-item" data-bs-toggle="collapse" data-bs-target=".quarto-sidebar-collapse-item"></div>
<!-- margin-sidebar -->
    <div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
        <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">On this page</h2>
   
  <ul>
  <li><a href="#the-frequentist-approach-to-statistics" id="toc-the-frequentist-approach-to-statistics" class="nav-link active" data-scroll-target="#the-frequentist-approach-to-statistics"><span class="header-section-number">0.1</span> The Frequentist Approach to Statistics</a></li>
  <li><a href="#the-bayesian-approach-to-statistics" id="toc-the-bayesian-approach-to-statistics" class="nav-link" data-scroll-target="#the-bayesian-approach-to-statistics"><span class="header-section-number">0.2</span> The Bayesian Approach to Statistics</a>
  <ul class="collapse">
  <li><a href="#the-bayesian-t-test" id="toc-the-bayesian-t-test" class="nav-link" data-scroll-target="#the-bayesian-t-test"><span class="header-section-number">0.2.1</span> The Bayesian t-test</a></li>
  <li><a href="#the-bayesian-chi-square-test" id="toc-the-bayesian-chi-square-test" class="nav-link" data-scroll-target="#the-bayesian-chi-square-test"><span class="header-section-number">0.2.2</span> The Bayesian chi-square test</a></li>
  <li><a href="#the-bayesian-linear-model" id="toc-the-bayesian-linear-model" class="nav-link" data-scroll-target="#the-bayesian-linear-model"><span class="header-section-number">0.2.3</span> The Bayesian linear model</a></li>
  <li><a href="#using-prior-data-in-a-bayesian-linear-model" id="toc-using-prior-data-in-a-bayesian-linear-model" class="nav-link" data-scroll-target="#using-prior-data-in-a-bayesian-linear-model"><span class="header-section-number">0.2.4</span> Using prior data in a Bayesian linear model</a></li>
  <li><a href="#generating-multiple-models-and-comparing-them" id="toc-generating-multiple-models-and-comparing-them" class="nav-link" data-scroll-target="#generating-multiple-models-and-comparing-them"><span class="header-section-number">0.2.5</span> Generating multiple models and comparing them</a></li>
  </ul></li>
  <li><a href="#tasks" id="toc-tasks" class="nav-link" data-scroll-target="#tasks"><span class="header-section-number">0.3</span> Tasks</a>
  <ul class="collapse">
  <li><a href="#task-1-bayesian-chi-square" id="toc-task-1-bayesian-chi-square" class="nav-link" data-scroll-target="#task-1-bayesian-chi-square"><span class="header-section-number">0.3.1</span> Task 1 Bayesian Chi Square</a></li>
  <li><a href="#task-2-bayesian-t-tests" id="toc-task-2-bayesian-t-tests" class="nav-link" data-scroll-target="#task-2-bayesian-t-tests"><span class="header-section-number">0.3.2</span> Task 2 Bayesian t-tests</a></li>
  <li><a href="#task-3-bayesian-linear-models" id="toc-task-3-bayesian-linear-models" class="nav-link" data-scroll-target="#task-3-bayesian-linear-models"><span class="header-section-number">0.3.3</span> Task 3 Bayesian linear models</a></li>
  <li><a href="#task-4-bayesian-linear-models" id="toc-task-4-bayesian-linear-models" class="nav-link" data-scroll-target="#task-4-bayesian-linear-models"><span class="header-section-number">0.3.4</span> Task 4 Bayesian linear models</a></li>
  <li><a href="#task-5-bayesian-comparison-of-models" id="toc-task-5-bayesian-comparison-of-models" class="nav-link" data-scroll-target="#task-5-bayesian-comparison-of-models"><span class="header-section-number">0.3.5</span> Task 5 Bayesian comparison of models</a></li>
  </ul></li>
  <li><a href="#further-reading" id="toc-further-reading" class="nav-link" data-scroll-target="#further-reading"><span class="header-section-number">0.4</span> Further reading</a></li>
  </ul>
</nav>
    </div>
<!-- main -->
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default"><nav class="quarto-page-breadcrumbs quarto-title-breadcrumbs d-none d-lg-block" aria-label="breadcrumb"><ol class="breadcrumb"><li class="breadcrumb-item"><a href="../chapters/06-1-SEM.html">SEM and Bayesian</a></li><li class="breadcrumb-item"><a href="../chapters/06-2-Bayesian.html">Bayesian Statistics</a></li></ol></nav>
<div class="quarto-title">
<h1 class="title">Bayesian Statistics</h1>
</div>



<div class="quarto-title-meta">

    
  
    
  </div>
  


</header>


<section id="the-frequentist-approach-to-statistics" class="level2" data-number="0.1">
<h2 data-number="0.1" class="anchored" data-anchor-id="the-frequentist-approach-to-statistics"><span class="header-section-number">0.1</span> The Frequentist Approach to Statistics</h2>
<p>The statistical methods you have encountered to this point, the t-tests, chi-squared tests and linear models, are examples of an approach to statistics labelled frequentist statistics. Typically these methods report p-values which indicate the probability, assuming that the null hypothesis is true, of obtaining similar or more extreme results. Frequentist methods calculate the probability of the occurrence of events based on the outcome of many trials.</p>
<p>However, frequentist statistics, because of the way the outcomes of tests are presented, can be hard to interpret. Consider the case of two sets of exam results, for class A and B, which are taught by different methods. We wish to determine if there is a statistically significant difference in means, to see if one approach to teaching is better than the other, so we perform a frequentist t-test.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb1"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1"></a>ClassA <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">54</span>,<span class="dv">53</span>,<span class="dv">72</span>,<span class="dv">31</span>,<span class="dv">25</span>,<span class="dv">34</span>,<span class="dv">87</span>,<span class="dv">45</span>,<span class="dv">26</span>,<span class="dv">42</span>,<span class="dv">54</span>,<span class="dv">58</span>,<span class="dv">80</span>)</span>
<span id="cb1-2"><a href="#cb1-2"></a>ClassB <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="dv">82</span>,<span class="dv">94</span>,<span class="dv">88</span>,<span class="dv">76</span>,<span class="dv">82</span>,<span class="dv">60</span>,<span class="dv">88</span>,<span class="dv">90</span>,<span class="dv">75</span>,<span class="dv">77</span>,<span class="dv">96</span>,<span class="dv">61</span>,<span class="dv">74</span>)</span>
<span id="cb1-3"><a href="#cb1-3"></a></span>
<span id="cb1-4"><a href="#cb1-4"></a><span class="fu">t.test</span>(ClassA, ClassB)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Welch Two Sample t-test

data:  ClassA and ClassB
t = -4.6276, df = 19.013, p-value = 0.0001833
alternative hypothesis: true difference in means is not equal to 0
95 percent confidence interval:
 -42.67437 -16.09486
sample estimates:
mean of x mean of y 
 50.84615  80.23077 </code></pre>
</div>
</div>
<p>In this case, the p-value of the frequentist t-test is 0.0002, less than 0.05. We conclude that, if we assume the null hypothesis (that the means of the classes are the same), there is a probability of 0.0002 (1 in 5000) than results like this, or more extreme, could have arisen by chance.</p>
<p>The p-value here can be thought of as indicating the probability of a false positive. That is, it reports the probability that a difference in means of this size or larger could have arise by chance. Alternatively, the p-value is sometimes described as a measure of how surprised one ought to be by the results - if we assume the classes should get the same results, the p-value of 0.0002 suggests we ought to be considerably surprised (shocked!) to get results as different as this (50 in one class, 80 in the other) by chance.</p>
<p>The trouble with the frequentist p-value is that is doesn’t tell us what we typically want to know - what is the probability that the scores in the condition group are different from the control (and hence there is a difference in the teaching approaches). The Frequentist approach reports, after a number of trials, the limit of the relative frequency of an event. For example, after 13 students in each class have sat the test, and assuming that the two classes have the same mean score, there is a 1 in 5000 chance that the results like this, or more extreme, would occur. This is not an intuitive approach to reporting probability - the Bayesian approach offers an alternative.</p>
</section>
<section id="the-bayesian-approach-to-statistics" class="level2" data-number="0.2">
<h2 data-number="0.2" class="anchored" data-anchor-id="the-bayesian-approach-to-statistics"><span class="header-section-number">0.2</span> The Bayesian Approach to Statistics</h2>
<p>The Bayesian approach was developed by the English statistician and Presbyterian minister, Thomas Bayes. The Bayesian approach proposes a different model to expressing the outcome of statistical tests. Bayesian statistics report a probability expressing a degree of belief an event. Central to Bayesian statistics is the assumption that the degree of belief should be revised based on prior knowledge. This contrasts with frequentist statistics in which the null hypothesis is assumed, even though it is rare to genuinely believe in the null hypothesis - there are rarely no differences between groups <span class="citation" data-cites="murphy1990if">(<a href="#ref-murphy1990if" role="doc-biblioref">Murphy 1990</a>)</span>. In Bayesian statistics, analysis is carried out in light of prior knowledge of probabilities of relevant events. In the case of the classes above, for example, information about prior achievement, and hence the likelihood of the two classes having the same mean score could be used in the calculation.</p>
<blockquote class="blockquote">
<p>“’The key ideas of Bayesian statistics: that probability is orderly opinion, and that inference from data is nothing other than the revision of such opinion in the light of relevant new information” <span class="citation" data-cites="edwards1963">(<a href="#ref-edwards1963" role="doc-biblioref">Edwards, Lindman, and Savage 1963, 194</a>)</span></p>
</blockquote>
<p>Bayes’ theorem can be stated mathematically as:<span class="math inline">\(P(A\vert B)=\frac{P(B \vert A)P(A)}{P(B)}, \text{ if } P(B) \neq 0\)</span></p>
<p>A and B represent two events. <span class="math inline">\(P(A)\)</span> represents the probability of A occurring and <span class="math inline">\(P(A)\)</span> the probability of B happening. The formula assumes that <span class="math inline">\(P(B)\ne0\)</span>, that is there is some probability the event B will happen.</p>
<p><span class="math inline">\(P(A\vert B)\)</span> is a conditional probability - that is, the probability that A will occur given that B has occurred.</p>
<p><span class="math inline">\(P(B\vert A)\)</span> is another conditional probability - this time, the probability that B will occur given that A has occurred.</p>
<p>We can see how the formula works in an example:</p>
<p>Imagine that the prevalence of students who have profound and multiple learning difficulties (PMLD) in state secondary schools in the UK is 1%. We might also know that the screening process for PMLD gives a false positive (i.e.&nbsp;incorrectly categorises a student with no learning difficulties with PMLD) 5% of the time.</p>
<p>A student receives a diagnosis of PMLD - what is the probability that they have PMLD?</p>
<p>We can use the formula to find the probability that the student has PMLD, given that they have a positive test <span class="math inline">\(P(HasPMLD\vert PositiveTest)\)</span>. But let us first consider the calculation intuitively.</p>
<p><span class="math inline">\(P(HasPMLD\vert PositiveTest)=\frac{P(PositiveTest \vert HasPMLD)P(HasPMLD)}{P(PositiveTest)}\)</span></p>
<p>If we select 1000 people at random for PMLD testing, 10 will have PMLD. 990 students will not have PMLD. Of those 990 people, 5% will receive a positive screening. 5% of 990 is 49.5 people. So there are 10 (correct screenings) + 49.5 (false positives) = 59.5 people who test positive. The probability that someone has PMLD, given a positive test is <span class="math inline">\(P(HasPMLD\vert PositiveTest)\)</span> is <span class="math inline">\(10/59.5=0.17\)</span> surprisingly low.</p>
<p>We can use the formula to get to the same result:</p>
<p><span class="math inline">\(P(HasPMLD\vert PositiveTest)=\frac{P(PositiveTest \vert HasPMLD)P(HasPMLD)}{P(PositiveTest)}\)</span></p>
<p><span class="math inline">\(P(PositiveTest \vert HasPMLD)=1\)</span></p>
<p><span class="math inline">\(P(HasPMLD)=0.01\)</span></p>
<p><span class="math inline">\(P(PositiveTest)=(1*10/1000)+(0.05*990/1000)=0.0595\)</span></p>
<p><span class="math inline">\(P(HasPSMLD\vert PositiveTest)=\frac{(1)(0.01)}{(0.0595)}=0.17\)</span></p>
<p>The example indicates the value of taking prior information into account when making inferences. Intuitively, it might be expected that, with the low rate of false positives (5%) a positive test would mean a high certainty of diagnosis. However, combined with knowledge of the prevalence of PMLD in the population, the probability of having PSMLD after a positive test is only around 1 in 5.</p>
<p>There are Bayesian versions of the inferential tests we have covered so far (t-tests, chi-squared, correlationa dn linear regression).</p>
<section id="the-bayesian-t-test" class="level3" data-number="0.2.1">
<h3 data-number="0.2.1" class="anchored" data-anchor-id="the-bayesian-t-test"><span class="header-section-number">0.2.1</span> The Bayesian t-test</h3>
<p>The <code>BayesFactor</code> package can be used to perform a Bayesian version of the t-test. Let us perform the Bayesian test on the same class data we used above, for which we found a p-value of 0.0002.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb3"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1"></a><span class="fu">library</span>(BayesFactor)</span>
<span id="cb3-2"><a href="#cb3-2"></a><span class="co"># Create two dummy class exam scores, as dataframes this time, as that is what the Bayesian t-test takes as an input</span></span>
<span id="cb3-3"><a href="#cb3-3"></a></span>
<span id="cb3-4"><a href="#cb3-4"></a>ClassA <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Scores =</span> <span class="fu">c</span>(<span class="dv">54</span>,<span class="dv">53</span>,<span class="dv">72</span>,<span class="dv">31</span>,<span class="dv">25</span>,<span class="dv">34</span>,<span class="dv">87</span>,<span class="dv">45</span>,<span class="dv">26</span>,<span class="dv">42</span>,<span class="dv">54</span>,<span class="dv">58</span>,<span class="dv">80</span>))</span>
<span id="cb3-5"><a href="#cb3-5"></a>ClassB <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Scores =</span> <span class="fu">c</span>(<span class="dv">82</span>,<span class="dv">94</span>,<span class="dv">88</span>,<span class="dv">76</span>,<span class="dv">82</span>,<span class="dv">60</span>,<span class="dv">88</span>,<span class="dv">90</span>,<span class="dv">75</span>,<span class="dv">77</span>,<span class="dv">96</span>,<span class="dv">61</span>,<span class="dv">74</span>))</span>
<span id="cb3-6"><a href="#cb3-6"></a></span>
<span id="cb3-7"><a href="#cb3-7"></a><span class="co"># Label the classes A and B</span></span>
<span id="cb3-8"><a href="#cb3-8"></a>ClassA <span class="ot">&lt;-</span> ClassA <span class="sc">%&gt;%</span></span>
<span id="cb3-9"><a href="#cb3-9"></a>  <span class="fu">mutate</span>(<span class="at">Class=</span><span class="st">"A"</span>)</span>
<span id="cb3-10"><a href="#cb3-10"></a></span>
<span id="cb3-11"><a href="#cb3-11"></a>ClassB <span class="ot">&lt;-</span> ClassB <span class="sc">%&gt;%</span></span>
<span id="cb3-12"><a href="#cb3-12"></a>  <span class="fu">mutate</span>(<span class="at">Class=</span><span class="st">"B"</span>)</span>
<span id="cb3-13"><a href="#cb3-13"></a></span>
<span id="cb3-14"><a href="#cb3-14"></a><span class="co"># Combine into one data frame</span></span>
<span id="cb3-15"><a href="#cb3-15"></a>Totaldata <span class="ot">&lt;-</span> <span class="fu">rbind</span>(ClassA, ClassB)</span>
<span id="cb3-16"><a href="#cb3-16"></a></span>
<span id="cb3-17"><a href="#cb3-17"></a><span class="co"># Perform the Bayesian test</span></span>
<span id="cb3-18"><a href="#cb3-18"></a><span class="fu">ttestBF</span>(<span class="at">data =</span> Totaldata, <span class="at">formula =</span> Scores <span class="sc">~</span> Class)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Alt., r=0.707 : 194.1877 ±0%

Against denominator:
  Null, mu1-mu2 = 0 
---
Bayes factor type: BFindepSample, JZS</code></pre>
</div>
</div>
<p>The value of interest here is the Bayes factor, 194.1877, followed by the confidence interval ±0%. The Bayes factor can be thought of as a measure of the relative likelihood of a difference (in this case, a different in scores between the groups). Here the factor can be interpreted to mean: It is 194 times more likely that there is a difference between the two classes than there is no difference.</p>
<p>By comparison with a p-value, which acts only as a cut of for significance, the Bayes factor tells you the relative likelihood, a more useful piece of information.</p>
<p>(Note that to calculate the Bayesian t-test, some assumptions have to be made. One is the assumption of a distribution of effect sizes, in this case a kind of distribution known as a Cauchy distribution is assumed, r=0.707 refers to a parameter of that distribution).</p>
<p>Null, mu1-mu2 = 0 tells us that the null hypothesis is that the means (the mus) of the two groups are the same.</p>
<p><code>Against denominator: Null, mu1-mu2 = 0</code> refers to the denominator (i.e the part below the line), in the Bayes theorem:</p>
<p><span class="math inline">\(P(A\vert B)=\frac{P(B \vert A)P(A)}{P(B)}, \text{ if } P(B) \neq 0\)</span></p>
<p>In this case <span class="math inline">\(P(B)\)</span> refers to the probability that there is no difference between the classes.</p>
</section>
<section id="the-bayesian-chi-square-test" class="level3" data-number="0.2.2">
<h3 data-number="0.2.2" class="anchored" data-anchor-id="the-bayesian-chi-square-test"><span class="header-section-number">0.2.2</span> The Bayesian chi-square test</h3>
<p>The <code>BayesFactor</code> package also contains a Bayesian version of the chi-square test. In the example below, there is some example data: the gender of 14 people is reported as well as whether each has a degree (expressed as 1 (has a degree), and 0 (has no degree)). The chi square test attempts to examine whether the distribution of degrees in the male and female groups is statistically signficant.</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb5"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb5-1"><a href="#cb5-1"></a><span class="co"># Create two a dataframe 1=has degree, 0=has no degree</span></span>
<span id="cb5-2"><a href="#cb5-2"></a>DegreeGender <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Gender =</span> <span class="fu">c</span>(<span class="st">"Male"</span>,<span class="st">"Male"</span>,<span class="st">"Female"</span>,<span class="st">"Male"</span>,<span class="st">"Female"</span>,<span class="st">"Female"</span>,</span>
<span id="cb5-3"><a href="#cb5-3"></a>                                      <span class="st">"Female"</span>,<span class="st">"Male"</span>,<span class="st">"Male"</span>,<span class="st">"Female"</span>,<span class="st">"Male"</span>,</span>
<span id="cb5-4"><a href="#cb5-4"></a>                                      <span class="st">"Female"</span>,<span class="st">"Female"</span>,<span class="st">"Male"</span>),</span>
<span id="cb5-5"><a href="#cb5-5"></a>                           <span class="at">Degree =</span> <span class="fu">c</span>(<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>,<span class="dv">1</span>,<span class="dv">0</span>))</span>
<span id="cb5-6"><a href="#cb5-6"></a></span>
<span id="cb5-7"><a href="#cb5-7"></a></span>
<span id="cb5-8"><a href="#cb5-8"></a><span class="co"># Create a contingency table</span></span>
<span id="cb5-9"><a href="#cb5-9"></a>conttab <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="at">data =</span> DegreeGender, <span class="sc">~</span> Degree <span class="sc">+</span> Gender)</span>
<span id="cb5-10"><a href="#cb5-10"></a>conttab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>      Gender
Degree Female Male
     0      5    3
     1      2    4</code></pre>
</div>
<div class="sourceCode cell-code" id="cb7"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb7-1"><a href="#cb7-1"></a><span class="co"># Perform the Bayesian chi-square test</span></span>
<span id="cb7-2"><a href="#cb7-2"></a><span class="fu">contingencyTableBF</span>(conttab, <span class="at">sampleType =</span> <span class="st">"jointMulti"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Non-indep. (a=1) : 1.351891 ±0%

Against denominator:
  Null, independence, a = 1 
---
Bayes factor type: BFcontingencyTable, joint multinomial</code></pre>
</div>
<div class="sourceCode cell-code" id="cb9"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb9-1"><a href="#cb9-1"></a><span class="co"># For comparison, perform the frequentist Chi square test</span></span>
<span id="cb9-2"><a href="#cb9-2"></a><span class="fu">chisq.test</span>(conttab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  conttab
X-squared = 0.29167, df = 1, p-value = 0.5892</code></pre>
</div>
</div>
<p>The outcome of the chi-square test, gives a Bayes factor of 1.351891. This value raises the question of how to interpret different values of Bayes factors. <span class="citation" data-cites="kass1995">Kass and Raftery (<a href="#ref-kass1995" role="doc-biblioref">1995</a>)</span> have suggested these labels for interpreting Bayes factors:</p>
<table class="table">
<thead>
<tr class="header">
<th>Bayes Factor</th>
<th>Strength of evidence</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>&lt;1</td>
<td>There is no difference.</td>
</tr>
<tr class="even">
<td>=1</td>
<td>Presence or absence of a difference is equally likely</td>
</tr>
<tr class="odd">
<td>1 to 3.2</td>
<td>Not worth more than a bare mention</td>
</tr>
<tr class="even">
<td>3.2-10</td>
<td>Substantial</td>
</tr>
<tr class="odd">
<td>10-100</td>
<td>Strong</td>
</tr>
<tr class="even">
<td>&gt;100</td>
<td>Decisive</td>
</tr>
</tbody>
</table>
<p>In the case of the chi-square test above, the Bayes factor of 1.351891 falls into the category of ‘Not worth more than a bare mention’. This coheres with the frequentist chi-square result, p-value = 0.5892, which is interpreted as implying, given the null hypothesis, there are no statistically significant differences between the two groups.</p>
</section>
<section id="the-bayesian-linear-model" class="level3" data-number="0.2.3">
<h3 data-number="0.2.3" class="anchored" data-anchor-id="the-bayesian-linear-model"><span class="header-section-number">0.2.3</span> The Bayesian linear model</h3>
<p>We covered linear models in an earlier sessions using the <code>lm</code> function - there is an alternative Bayesian version, in the <code>brms</code> package.</p>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>Note that, when using <code>brm</code> the function can take some time to run!</p>
</div>
</div>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-6"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy"><code class="sourceCode r"><span id="annotated-cell-6-1"><a href="#annotated-cell-6-1"></a><span class="co"># Load the package to perform the Bayesian linear model</span></span>
<span id="annotated-cell-6-2"><a href="#annotated-cell-6-2"></a><span class="fu">library</span>(brms)</span>
<span id="annotated-cell-6-3"><a href="#annotated-cell-6-3"></a><span class="co"># BRM is not the quickest Bayesian lm function, but it allows the calculation of an R2 equivalent which is really helpful</span></span>
<span id="annotated-cell-6-4"><a href="#annotated-cell-6-4"></a></span>
<span id="annotated-cell-6-5"><a href="#annotated-cell-6-5"></a><span class="co"># Create a dummy data frame with a random normally distributed variable, Var 1. Then add a second random variable offset from the first</span></span>
<span id="annotated-cell-6-6"><a href="#annotated-cell-6-6"></a>testdata <span class="ot">&lt;-</span> <span class="fu">data.frame</span>(<span class="at">Var1 =</span> <span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean=</span><span class="dv">25</span>, <span class="at">sd=</span><span class="dv">10</span>))</span>
<span id="annotated-cell-6-7"><a href="#annotated-cell-6-7"></a></span>
<span id="annotated-cell-6-8"><a href="#annotated-cell-6-8"></a>testdata <span class="ot">&lt;-</span> testdata <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-6-9"><a href="#annotated-cell-6-9"></a>  <span class="fu">mutate</span>(<span class="at">Var2 =</span> Var1 <span class="sc">+</span> <span class="fu">rnorm</span>(<span class="dv">50</span>, <span class="at">mean=</span><span class="dv">5</span>, <span class="at">sd=</span><span class="dv">2</span>))</span>
<span id="annotated-cell-6-10"><a href="#annotated-cell-6-10"></a></span>
<span id="annotated-cell-6-11"><a href="#annotated-cell-6-11"></a><span class="co"># Plot the data</span></span>
<span id="annotated-cell-6-12"><a href="#annotated-cell-6-12"></a><span class="fu">ggplot</span>(<span class="at">data=</span>testdata, <span class="fu">aes</span>(<span class="at">x=</span>Var1, <span class="at">y=</span>Var2)) <span class="sc">+</span></span>
<span id="annotated-cell-6-13"><a href="#annotated-cell-6-13"></a>  <span class="fu">geom_point</span>()</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-7" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="2" data-code-annotation="4">line 5 run a frequentist linear model on the data using <code>lm</code></span>
</dd>
<dt data-target-cell="annotated-cell-7" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="3" data-code-annotation="5">line 6 print the output of the frequentist model</span>
</dd>
<dt data-target-cell="annotated-cell-7" data-target-annotation="6">6</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="6" data-code-annotation="6">line 7 use the <code>brm</code> function to run an equivalent Bayesian linear model</span>
</dd>
<dt data-target-cell="annotated-cell-7" data-target-annotation="7">7</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="7" data-code-annotation="7">line 8 print the output of the Bayesian model</span>
</dd>
<dt data-target-cell="annotated-cell-7" data-target-annotation="8">8</dt>
<dd>
<span data-code-cell="annotated-cell-7" data-code-lines="10" data-code-annotation="8">line 9 use the <code>bayes_R2</code> function to find the R2 equivalent for the Bayesian linear model.</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-2-Bayesian_files/figure-html/unnamed-chunk-4-1.png" class="img-fluid figure-img" style="width:95.0%"></p>
</figure>
</div>
</div>
<div class="sourceCode cell-code" id="annotated-cell-7"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-7-1"><a href="#annotated-cell-7-1"></a><span class="co"># Perform the frequentist linear model</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-7-2" class="code-annotation-target"><a href="#annotated-cell-7-2"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data=</span>testdata, Var1 <span class="sc">~</span> Var2)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-7-3" class="code-annotation-target"><a href="#annotated-cell-7-3"></a><span class="fu">summary</span>(mod)</span>
<span id="annotated-cell-7-4"><a href="#annotated-cell-7-4"></a></span>
<span id="annotated-cell-7-5"><a href="#annotated-cell-7-5"></a><span class="co"># Perform the Bayesian linear model</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="6" onclick="event.preventDefault();">6</a><span id="annotated-cell-7-6" class="code-annotation-target"><a href="#annotated-cell-7-6"></a>mod <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data=</span>testdata, Var1 <span class="sc">~</span> Var2)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="7" onclick="event.preventDefault();">7</a><span id="annotated-cell-7-7" class="code-annotation-target"><a href="#annotated-cell-7-7"></a><span class="fu">summary</span>(mod)</span>
<span id="annotated-cell-7-8"><a href="#annotated-cell-7-8"></a></span>
<span id="annotated-cell-7-9"><a href="#annotated-cell-7-9"></a><span class="co"># Calculate the Bayesian equivalent of R2</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-7" data-target-annotation="8" onclick="event.preventDefault();">8</a><span id="annotated-cell-7-10" class="code-annotation-target"><a href="#annotated-cell-7-10"></a><span class="fu">bayes_R2</span>(mod)</span>
<span id="annotated-cell-7-11"><a href="#annotated-cell-7-11"></a></span>
<span id="annotated-cell-7-12"><a href="#annotated-cell-7-12"></a><span class="co"># The R2 for the model is 0.97 so 97% of the variance is explained</span></span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>
Call:
lm(formula = Var1 ~ Var2, data = testdata)

Residuals:
    Min      1Q  Median      3Q     Max 
-3.9838 -1.5178  0.0805  1.2679  3.4607 

Coefficients:
            Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) -4.60499    0.69660  -6.611 2.91e-08 ***
Var2         0.96949    0.02296  42.218  &lt; 2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 1.796 on 48 degrees of freedom
Multiple R-squared:  0.9738,    Adjusted R-squared:  0.9732 
F-statistic:  1782 on 1 and 48 DF,  p-value: &lt; 2.2e-16

Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB foo.c
using C compiler: ‘Apple clang version 15.0.0 (clang-1500.1.0.2.5)’
using SDK: ‘MacOSX14.2.sdk’
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Users/k1765032/Library/R/arm64/4.3/library/Rcpp/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/unsupported"  -I"/Users/k1765032/Library/R/arm64/4.3/library/BH/include" -I"/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/src/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppParallel/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/rstan/include" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DUSE_STANC3 -DSTRICT_R_HEADERS  -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -D_HAS_AUTO_PTR_ETC=0  -include '/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp'  -D_REENTRANT -DRCPP_PARALLEL_USE_TBB=1   -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c foo.c -o foo.o
In file included from &lt;built-in&gt;:1:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:22:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/Dense:1:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/Core:19:
/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:679:10: fatal error: 'cmath' file not found
#include &lt;cmath&gt;
         ^~~~~~~
1 error generated.
make: *** [foo.o] Error 1

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).
Chain 1: 
Chain 1: Gradient evaluation took 4.2e-05 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.42 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 1: 
Chain 1:  Elapsed Time: 0.014 seconds (Warm-up)
Chain 1:                0.009 seconds (Sampling)
Chain 1:                0.023 seconds (Total)
Chain 1: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 2).
Chain 2: 
Chain 2: Gradient evaluation took 3e-06 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.03 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2: 
Chain 2: 
Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 2: 
Chain 2:  Elapsed Time: 0.013 seconds (Warm-up)
Chain 2:                0.012 seconds (Sampling)
Chain 2:                0.025 seconds (Total)
Chain 2: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 3).
Chain 3: 
Chain 3: Gradient evaluation took 2e-06 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.02 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3: 
Chain 3: 
Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 3: 
Chain 3:  Elapsed Time: 0.014 seconds (Warm-up)
Chain 3:                0.012 seconds (Sampling)
Chain 3:                0.026 seconds (Total)
Chain 3: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 4).
Chain 4: 
Chain 4: Gradient evaluation took 4e-06 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.04 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4: 
Chain 4: 
Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 4: 
Chain 4:  Elapsed Time: 0.013 seconds (Warm-up)
Chain 4:                0.012 seconds (Sampling)
Chain 4:                0.025 seconds (Total)
Chain 4: 
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: Var1 ~ Var2 
   Data: testdata (Number of observations: 50) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    -4.59      0.72    -6.00    -3.16 1.00     4086     2617
Var2          0.97      0.02     0.92     1.02 1.00     4118     2818

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma     1.84      0.19     1.51     2.27 1.00     3797     2989

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).
    Estimate  Est.Error      Q2.5     Q97.5
R2 0.9731298 0.00161173 0.9686994 0.9744436</code></pre>
</div>
</div>
<p>You can see that the frequentist and Bayesian approaches give similar results:</p>
<table class="table">
<thead>
<tr class="header">
<th>Variable</th>
<th>Frequentist (<code>lm</code>)</th>
<th>Bayesian (<code>brm</code>)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td>Intercept</td>
<td>-4.3068</td>
<td>-4.33</td>
</tr>
<tr class="even">
<td>Beta</td>
<td>0.96280</td>
<td>0.96</td>
</tr>
<tr class="odd">
<td>R^2</td>
<td>0.9649</td>
<td>0.9641715</td>
</tr>
</tbody>
</table>
</section>
<section id="using-prior-data-in-a-bayesian-linear-model" class="level3" data-number="0.2.4">
<h3 data-number="0.2.4" class="anchored" data-anchor-id="using-prior-data-in-a-bayesian-linear-model"><span class="header-section-number">0.2.4</span> Using prior data in a Bayesian linear model</h3>
<p>A central principle of Bayesian statistics is that a model is based on knowledge of prior outcomes. The Bayesian Regression Model function <code>brm</code> in the <code>brms</code> package extends the <code>lm</code> function by allowing us to provide a prior model of the independent variable. We do this by passing the mean and standard deviation of our independent variable to the <code>set_prior</code> function (we also specify the shape of the distribution, in our case, normal, and specify the name of our independent variable (<code>PV1MATH</code>)). To use as prior data, you can download the PISA 2018 data <a href="../Users/k1765032/Library/CloudStorage/OneDrive-King'sCollegeLondon/QERKCL_PISA/data/pisa/2018/PISA_student_2018.parquet">here</a>.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-8"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-8-1"><a href="#annotated-cell-8-1"></a><span class="co"># To predict 2022 PISA data, I am going to use prior information from the 2018 results</span></span>
<span id="annotated-cell-8-2"><a href="#annotated-cell-8-2"></a><span class="co">#PISA2015studentbayes &lt;- read_parquet("/Users/k1765032/Library/CloudStorage/GoogleDrive-richardandrewbrock@gmail.com/.shortcut-targets-by-id/1c3CkaEBOICzepArDfjQUP34W2BYhFjM4/PISR/Data/PISA/2015/PISA2015studentbayes.parquet")</span></span>
<span id="annotated-cell-8-3"><a href="#annotated-cell-8-3"></a></span>
<span id="annotated-cell-8-4"><a href="#annotated-cell-8-4"></a></span>
<span id="annotated-cell-8-5"><a href="#annotated-cell-8-5"></a><span class="co"># Find the prior distribution of UK mathematics scores we expect from previous years </span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-8-6" class="code-annotation-target"><a href="#annotated-cell-8-6"></a>math_summary <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-8-7" class="code-annotation-target"><a href="#annotated-cell-8-7"></a>  <span class="fu">select</span>(PV1MATH, CNT) <span class="sc">%&gt;%</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-8-8" class="code-annotation-target"><a href="#annotated-cell-8-8"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-8-9" class="code-annotation-target"><a href="#annotated-cell-8-9"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(PV1MATH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>),</span>
<span id="annotated-cell-8-10"><a href="#annotated-cell-8-10"></a>            <span class="at">sd =</span> <span class="fu">sd</span>(PV1MATH, <span class="at">na.rm =</span> <span class="cn">TRUE</span>))</span>
<span id="annotated-cell-8-11"><a href="#annotated-cell-8-11"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-8-12" class="code-annotation-target"><a href="#annotated-cell-8-12"></a>math_summary</span>
<span id="annotated-cell-8-13"><a href="#annotated-cell-8-13"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="6" onclick="event.preventDefault();">6</a><span id="annotated-cell-8-14" class="code-annotation-target"><a href="#annotated-cell-8-14"></a>math_mean <span class="ot">&lt;-</span> math_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(mean)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="7" onclick="event.preventDefault();">7</a><span id="annotated-cell-8-15" class="code-annotation-target"><a href="#annotated-cell-8-15"></a>math_sd   <span class="ot">&lt;-</span> math_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(sd)</span>
<span id="annotated-cell-8-16"><a href="#annotated-cell-8-16"></a></span>
<span id="annotated-cell-8-17"><a href="#annotated-cell-8-17"></a><span class="fu">library</span>(brms)</span>
<span id="annotated-cell-8-18"><a href="#annotated-cell-8-18"></a></span>
<span id="annotated-cell-8-19"><a href="#annotated-cell-8-19"></a><span class="co"># Specify the prior distribution using set_prior from the `BMS` package</span></span>
<span id="annotated-cell-8-20"><a href="#annotated-cell-8-20"></a></span>
<span id="annotated-cell-8-21"><a href="#annotated-cell-8-21"></a>prior2018 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="fu">glue</span>(<span class="st">"normal({math_mean},{math_sd})"</span>), </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="8" onclick="event.preventDefault();">8</a><span id="annotated-cell-8-22" class="code-annotation-target"><a href="#annotated-cell-8-22"></a>                         <span class="at">class =</span> <span class="st">"b"</span>, <span class="at">coef =</span> <span class="st">"PV1MATH"</span>))</span>
<span id="annotated-cell-8-23"><a href="#annotated-cell-8-23"></a></span>
<span id="annotated-cell-8-24"><a href="#annotated-cell-8-24"></a><span class="co"># Create the data frame of UK scores in 2018 to model</span></span>
<span id="annotated-cell-8-25"><a href="#annotated-cell-8-25"></a>UKPISA_2022 <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="9" onclick="event.preventDefault();">9</a><span id="annotated-cell-8-26" class="code-annotation-target"><a href="#annotated-cell-8-26"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>)</span>
<span id="annotated-cell-8-27"><a href="#annotated-cell-8-27"></a></span>
<span id="annotated-cell-8-28"><a href="#annotated-cell-8-28"></a><span class="co"># Use the Bayesian regression model function 'brm' to fir the model, specifying the prior</span></span>
<span id="annotated-cell-8-29"><a href="#annotated-cell-8-29"></a>modbay <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> UKPISA_2022, </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="10" onclick="event.preventDefault();">10</a><span id="annotated-cell-8-30" class="code-annotation-target"><a href="#annotated-cell-8-30"></a>              <span class="at">formula =</span> PV1SCIE <span class="sc">~</span> PV1MATH, <span class="at">prior =</span> prior2018)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="11" onclick="event.preventDefault();">11</a><span id="annotated-cell-8-31" class="code-annotation-target"><a href="#annotated-cell-8-31"></a><span class="fu">summary</span>(modbay)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="12" onclick="event.preventDefault();">12</a><span id="annotated-cell-8-32" class="code-annotation-target"><a href="#annotated-cell-8-32"></a><span class="fu">bayes_R2</span>(modbay)</span>
<span id="annotated-cell-8-33"><a href="#annotated-cell-8-33"></a></span>
<span id="annotated-cell-8-34"><a href="#annotated-cell-8-34"></a><span class="co"># Compare to the simple linear model</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="13" onclick="event.preventDefault();">13</a><span id="annotated-cell-8-35" class="code-annotation-target"><a href="#annotated-cell-8-35"></a>mod <span class="ot">&lt;-</span> <span class="fu">lm</span>(<span class="at">data =</span> UKPISA_2022,</span>
<span id="annotated-cell-8-36"><a href="#annotated-cell-8-36"></a>          <span class="at">formula =</span> PV1SCIE <span class="sc">~</span> PV1MATH)</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-8" data-target-annotation="14" onclick="event.preventDefault();">14</a><span id="annotated-cell-8-37" class="code-annotation-target"><a href="#annotated-cell-8-37"></a><span class="fu">summary</span>(mod)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-8" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="6" data-code-annotation="1">line 1 Pipe the PISA_2022 data into a new data frame <code>math_summary</code></span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="7" data-code-annotation="2">line 2 Select the maths and country items</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="8" data-code-annotation="3">line 3 Filter for the UK</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="9" data-code-annotation="4">line 4 Summarise the mean and standard deviation of the maths scores in the UK</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="12" data-code-annotation="5">line 5 Print the summary table</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="6">6</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="14" data-code-annotation="6">line 6 Use <code>pull</code> to assign the mean to a new variable <code>math_mean</code></span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="7">7</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="15" data-code-annotation="7">line 7 Use <code>pull</code> to assign the standard deviation to a new variable <code>math_sd</code></span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="8">8</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="22" data-code-annotation="8">line 10 Create the prior distribution. Here we use data from a previous PISA data set, the 2018 data. We first use glue to create the label for the distribution. The type of prior distribution is specified by some text, e.g.&nbsp;<code>"normal(0, 2)"</code> which sets the prior distribution to be a normal distribution of mean 0 and standard deviation 2. We use the <code>glue</code> function to join our calculated <code>math_mean</code> and <code>math_sd</code> with the word normal to create a string describing our prior The class is set to “b” the default, for fixed effects, and we specify the <code>coef</code> as the variable of interest <code>PV1MATH</code>.</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="9">9</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="26" data-code-annotation="9">line 12 We create data frame on which to run the model, 2022 maths data in the UK</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="10">10</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="30" data-code-annotation="10">line 14 We run the model on the 2022 data, specifying the 2018 data as the prior distribution</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="11">11</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="31" data-code-annotation="11">line 15 Print the summary</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="12">12</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="32" data-code-annotation="12">line 16 Print the R<sup>2</sup> equivalent</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="13">13</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="35" data-code-annotation="13">line 17 Run the frequentist linear model as a comparison</span>
</dd>
<dt data-target-cell="annotated-cell-8" data-target-annotation="14">14</dt>
<dd>
<span data-code-cell="annotated-cell-8" data-code-lines="37" data-code-annotation="14">line 19 Print the frequentist linear model</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   mean    sd
  &lt;dbl&gt; &lt;dbl&gt;
1  497.  89.9
Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB foo.c
using C compiler: ‘Apple clang version 15.0.0 (clang-1500.1.0.2.5)’
using SDK: ‘MacOSX14.2.sdk’
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Users/k1765032/Library/R/arm64/4.3/library/Rcpp/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/unsupported"  -I"/Users/k1765032/Library/R/arm64/4.3/library/BH/include" -I"/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/src/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppParallel/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/rstan/include" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DUSE_STANC3 -DSTRICT_R_HEADERS  -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -D_HAS_AUTO_PTR_ETC=0  -include '/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp'  -D_REENTRANT -DRCPP_PARALLEL_USE_TBB=1   -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c foo.c -o foo.o
In file included from &lt;built-in&gt;:1:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:22:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/Dense:1:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/Core:19:
/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:679:10: fatal error: 'cmath' file not found
#include &lt;cmath&gt;
         ^~~~~~~
1 error generated.
make: *** [foo.o] Error 1

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).
Chain 1: 
Chain 1: Gradient evaluation took 4e-05 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.4 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 1: 
Chain 1:  Elapsed Time: 0.42 seconds (Warm-up)
Chain 1:                0.128 seconds (Sampling)
Chain 1:                0.548 seconds (Total)
Chain 1: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 2).
Chain 2: 
Chain 2: Gradient evaluation took 2.4e-05 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.24 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2: 
Chain 2: 
Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 2: 
Chain 2:  Elapsed Time: 0.285 seconds (Warm-up)
Chain 2:                0.122 seconds (Sampling)
Chain 2:                0.407 seconds (Total)
Chain 2: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 3).
Chain 3: 
Chain 3: Gradient evaluation took 2.4e-05 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.24 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3: 
Chain 3: 
Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 3: 
Chain 3:  Elapsed Time: 0.286 seconds (Warm-up)
Chain 3:                0.126 seconds (Sampling)
Chain 3:                0.412 seconds (Total)
Chain 3: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 4).
Chain 4: 
Chain 4: Gradient evaluation took 2.3e-05 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.23 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4: 
Chain 4: 
Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 4: 
Chain 4:  Elapsed Time: 0.315 seconds (Warm-up)
Chain 4:                0.112 seconds (Sampling)
Chain 4:                0.427 seconds (Total)
Chain 4: 
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: PV1SCIE ~ PV1MATH 
   Data: UKPISA_2022 (Number of observations: 12972) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    42.39      2.34    37.70    46.88 1.00     5734     3323
PV1MATH       0.93      0.00     0.92     0.94 1.00     5166     3265

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma    50.75      0.32    50.13    51.40 1.00     3859     3156

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).
   Estimate   Est.Error      Q2.5     Q97.5
R2 0.753228 0.001912606 0.7494612 0.7569226

Call:
lm(formula = PV1SCIE ~ PV1MATH, data = UKPISA_2022)

Residuals:
     Min       1Q   Median       3Q      Max 
-237.834  -32.731    0.422   32.790  214.878 

Coefficients:
             Estimate Std. Error t value Pr(&gt;|t|)    
(Intercept) 42.333528   2.304412   18.37   &lt;2e-16 ***
PV1MATH      0.932418   0.004685  199.00   &lt;2e-16 ***
---
Signif. codes:  0 '***' 0.001 '**' 0.01 '*' 0.05 '.' 0.1 ' ' 1

Residual standard error: 50.74 on 12970 degrees of freedom
Multiple R-squared:  0.7533,    Adjusted R-squared:  0.7533 
F-statistic: 3.96e+04 on 1 and 12970 DF,  p-value: &lt; 2.2e-16</code></pre>
</div>
</div>
<p>Another useful feature of Bayesian models is that the model parameters, e.g.&nbsp;the intercept and coefficient, are not represented only as single values, but as distributions. This gives greater insight into the fit of the model</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-9"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-9-1"><a href="#annotated-cell-9-1"></a><span class="co"># What's nice with a Bayesian model is our model parameters are not simply values, but probability distributions which gives more insight into the confidence in the model</span></span>
<span id="annotated-cell-9-2"><a href="#annotated-cell-9-2"></a><span class="co"># For example, lets predict science scores based on mathematics scores and reading scores</span></span>
<span id="annotated-cell-9-3"><a href="#annotated-cell-9-3"></a><span class="co"># Find the prior distribution of UK mathematics scores we expect from previous years </span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-9-4" class="code-annotation-target"><a href="#annotated-cell-9-4"></a>math_summary <span class="ot">&lt;-</span>PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-9-5"><a href="#annotated-cell-9-5"></a>  <span class="fu">select</span>(PV1MATH,CNT) <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-9-6"><a href="#annotated-cell-9-6"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-9-7"><a href="#annotated-cell-9-7"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="annotated-cell-9-8"><a href="#annotated-cell-9-8"></a>            <span class="at">sd   =</span> <span class="fu">sd</span>(PV1MATH, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="annotated-cell-9-9"><a href="#annotated-cell-9-9"></a>math_summary</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-9-10" class="code-annotation-target"><a href="#annotated-cell-9-10"></a>math_mean <span class="ot">&lt;-</span> math_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(mean)</span>
<span id="annotated-cell-9-11"><a href="#annotated-cell-9-11"></a>math_sd   <span class="ot">&lt;-</span> math_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(sd)</span>
<span id="annotated-cell-9-12"><a href="#annotated-cell-9-12"></a> </span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-9-13" class="code-annotation-target"><a href="#annotated-cell-9-13"></a>read_summary <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-9-14"><a href="#annotated-cell-9-14"></a>  <span class="fu">select</span>(PV1READ, CNT) <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-9-15"><a href="#annotated-cell-9-15"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-9-16"><a href="#annotated-cell-9-16"></a>  <span class="fu">summarise</span>(<span class="at">mean =</span> <span class="fu">mean</span>(PV1READ, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="annotated-cell-9-17"><a href="#annotated-cell-9-17"></a>            <span class="at">sd   =</span> <span class="fu">sd</span>(PV1READ, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="annotated-cell-9-18"><a href="#annotated-cell-9-18"></a>read_summary</span>
<span id="annotated-cell-9-19"><a href="#annotated-cell-9-19"></a>read_mean <span class="ot">&lt;-</span> read_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(mean)</span>
<span id="annotated-cell-9-20"><a href="#annotated-cell-9-20"></a>read_sd   <span class="ot">&lt;-</span> read_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(sd)</span>
<span id="annotated-cell-9-21"><a href="#annotated-cell-9-21"></a></span>
<span id="annotated-cell-9-22"><a href="#annotated-cell-9-22"></a><span class="co"># Specify the prior distribution using set priors from the `BMS` package</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-9-23" class="code-annotation-target"><a href="#annotated-cell-9-23"></a>prior2018 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="fu">glue</span>(<span class="st">"normal({math_mean},{math_sd})"</span>),</span>
<span id="annotated-cell-9-24"><a href="#annotated-cell-9-24"></a>                         <span class="at">class =</span> <span class="st">"b"</span>, <span class="at">coef =</span> <span class="st">"PV1MATH"</span>),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-9-25" class="code-annotation-target"><a href="#annotated-cell-9-25"></a>               <span class="fu">set_prior</span>(<span class="fu">glue</span>(<span class="st">"normal({read_mean},{read_sd})"</span>),</span>
<span id="annotated-cell-9-26"><a href="#annotated-cell-9-26"></a>                         <span class="at">class =</span> <span class="st">"b"</span>, <span class="at">coef =</span> <span class="st">"PV1READ"</span>))</span>
<span id="annotated-cell-9-27"><a href="#annotated-cell-9-27"></a></span>
<span id="annotated-cell-9-28"><a href="#annotated-cell-9-28"></a><span class="co"># Create the data frame of UK scores in 2022 to model</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="6" onclick="event.preventDefault();">6</a><span id="annotated-cell-9-29" class="code-annotation-target"><a href="#annotated-cell-9-29"></a>UKPISA_2022 <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-9-30"><a href="#annotated-cell-9-30"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>)</span>
<span id="annotated-cell-9-31"><a href="#annotated-cell-9-31"></a></span>
<span id="annotated-cell-9-32"><a href="#annotated-cell-9-32"></a><span class="co"># Use the Bayesian regression model function 'brm' to fit the model, specifying the prior</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="7" onclick="event.preventDefault();">7</a><span id="annotated-cell-9-33" class="code-annotation-target"><a href="#annotated-cell-9-33"></a>modbay <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> UKPISA_2022,</span>
<span id="annotated-cell-9-34"><a href="#annotated-cell-9-34"></a>              <span class="at">formula =</span> PV1SCIE <span class="sc">~</span> PV1MATH <span class="sc">+</span> PV1READ, <span class="at">prior =</span> prior2018)</span>
<span id="annotated-cell-9-35"><a href="#annotated-cell-9-35"></a><span class="fu">summary</span>(modbay)</span>
<span id="annotated-cell-9-36"><a href="#annotated-cell-9-36"></a><span class="fu">bayes_R2</span>(modbay)</span>
<span id="annotated-cell-9-37"><a href="#annotated-cell-9-37"></a></span>
<span id="annotated-cell-9-38"><a href="#annotated-cell-9-38"></a><span class="co"># Plot the distribution of the coefficients</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-9" data-target-annotation="8" onclick="event.preventDefault();">8</a><span id="annotated-cell-9-39" class="code-annotation-target"><a href="#annotated-cell-9-39"></a><span class="fu">plot</span>(modbay)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-9" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="4" data-code-annotation="1">line 1 Pipe the PISA_2022 data into a new data frame <code>math_summary</code> in the UK</span>
</dd>
<dt data-target-cell="annotated-cell-9" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="10" data-code-annotation="2">line 6 Use <code>pull</code> to assign the mean and sd to a new variable <code>math_mean</code> <code>math_sd</code></span>
</dd>
<dt data-target-cell="annotated-cell-9" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="13" data-code-annotation="3">line 9 As for maths, create a summary of reading scores in the UK and calculate the <code>read_mean</code> and <code>read_sd</code></span>
</dd>
<dt data-target-cell="annotated-cell-9" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="23" data-code-annotation="4">line 17 Set the prior distributions, as above, here for maths</span>
</dd>
<dt data-target-cell="annotated-cell-9" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="25" data-code-annotation="5">line 19 Set the prior distribution for reading</span>
</dd>
<dt data-target-cell="annotated-cell-9" data-target-annotation="6">6</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="29" data-code-annotation="6">line 22 Create a data frame of 2022 scores in the UK to run the model on</span>
</dd>
<dt data-target-cell="annotated-cell-9" data-target-annotation="7">7</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="33" data-code-annotation="7">line 23 Run the Bayesian model</span>
</dd>
<dt data-target-cell="annotated-cell-9" data-target-annotation="8">8</dt>
<dd>
<span data-code-cell="annotated-cell-9" data-code-lines="39" data-code-annotation="8">line 27 plot a graph of the distribution of the coefficients</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-2-Bayesian_files/figure-html/unnamed-chunk-6-1.png" class="img-fluid figure-img" style="width:95.0%"></p>
</figure>
</div>
</div>
<div class="cell-output cell-output-stdout">
<pre><code># A tibble: 1 × 2
   mean    sd
  &lt;dbl&gt; &lt;dbl&gt;
1  497.  89.9
# A tibble: 1 × 2
   mean    sd
  &lt;dbl&gt; &lt;dbl&gt;
1  500.  97.8
Running /Library/Frameworks/R.framework/Resources/bin/R CMD SHLIB foo.c
using C compiler: ‘Apple clang version 15.0.0 (clang-1500.1.0.2.5)’
using SDK: ‘MacOSX14.2.sdk’
clang -arch arm64 -I"/Library/Frameworks/R.framework/Resources/include" -DNDEBUG   -I"/Users/k1765032/Library/R/arm64/4.3/library/Rcpp/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/unsupported"  -I"/Users/k1765032/Library/R/arm64/4.3/library/BH/include" -I"/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/src/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/RcppParallel/include/"  -I"/Users/k1765032/Library/R/arm64/4.3/library/rstan/include" -DEIGEN_NO_DEBUG  -DBOOST_DISABLE_ASSERTS  -DBOOST_PENDING_INTEGER_LOG2_HPP  -DSTAN_THREADS  -DUSE_STANC3 -DSTRICT_R_HEADERS  -DBOOST_PHOENIX_NO_VARIADIC_EXPRESSION  -D_HAS_AUTO_PTR_ETC=0  -include '/Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp'  -D_REENTRANT -DRCPP_PARALLEL_USE_TBB=1   -I/opt/R/arm64/include    -fPIC  -falign-functions=64 -Wall -g -O2  -c foo.c -o foo.o
In file included from &lt;built-in&gt;:1:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/StanHeaders/include/stan/math/prim/fun/Eigen.hpp:22:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/Dense:1:
In file included from /Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/Core:19:
/Users/k1765032/Library/R/arm64/4.3/library/RcppEigen/include/Eigen/src/Core/util/Macros.h:679:10: fatal error: 'cmath' file not found
#include &lt;cmath&gt;
         ^~~~~~~
1 error generated.
make: *** [foo.o] Error 1

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 1).
Chain 1: 
Chain 1: Gradient evaluation took 4.4e-05 seconds
Chain 1: 1000 transitions using 10 leapfrog steps per transition would take 0.44 seconds.
Chain 1: Adjust your expectations accordingly!
Chain 1: 
Chain 1: 
Chain 1: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 1: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 1: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 1: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 1: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 1: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 1: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 1: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 1: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 1: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 1: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 1: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 1: 
Chain 1:  Elapsed Time: 0.592 seconds (Warm-up)
Chain 1:                0.263 seconds (Sampling)
Chain 1:                0.855 seconds (Total)
Chain 1: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 2).
Chain 2: 
Chain 2: Gradient evaluation took 3e-05 seconds
Chain 2: 1000 transitions using 10 leapfrog steps per transition would take 0.3 seconds.
Chain 2: Adjust your expectations accordingly!
Chain 2: 
Chain 2: 
Chain 2: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 2: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 2: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 2: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 2: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 2: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 2: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 2: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 2: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 2: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 2: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 2: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 2: 
Chain 2:  Elapsed Time: 0.489 seconds (Warm-up)
Chain 2:                0.262 seconds (Sampling)
Chain 2:                0.751 seconds (Total)
Chain 2: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 3).
Chain 3: 
Chain 3: Gradient evaluation took 3.9e-05 seconds
Chain 3: 1000 transitions using 10 leapfrog steps per transition would take 0.39 seconds.
Chain 3: Adjust your expectations accordingly!
Chain 3: 
Chain 3: 
Chain 3: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 3: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 3: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 3: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 3: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 3: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 3: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 3: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 3: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 3: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 3: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 3: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 3: 
Chain 3:  Elapsed Time: 0.665 seconds (Warm-up)
Chain 3:                0.292 seconds (Sampling)
Chain 3:                0.957 seconds (Total)
Chain 3: 

SAMPLING FOR MODEL 'anon_model' NOW (CHAIN 4).
Chain 4: 
Chain 4: Gradient evaluation took 3.4e-05 seconds
Chain 4: 1000 transitions using 10 leapfrog steps per transition would take 0.34 seconds.
Chain 4: Adjust your expectations accordingly!
Chain 4: 
Chain 4: 
Chain 4: Iteration:    1 / 2000 [  0%]  (Warmup)
Chain 4: Iteration:  200 / 2000 [ 10%]  (Warmup)
Chain 4: Iteration:  400 / 2000 [ 20%]  (Warmup)
Chain 4: Iteration:  600 / 2000 [ 30%]  (Warmup)
Chain 4: Iteration:  800 / 2000 [ 40%]  (Warmup)
Chain 4: Iteration: 1000 / 2000 [ 50%]  (Warmup)
Chain 4: Iteration: 1001 / 2000 [ 50%]  (Sampling)
Chain 4: Iteration: 1200 / 2000 [ 60%]  (Sampling)
Chain 4: Iteration: 1400 / 2000 [ 70%]  (Sampling)
Chain 4: Iteration: 1600 / 2000 [ 80%]  (Sampling)
Chain 4: Iteration: 1800 / 2000 [ 90%]  (Sampling)
Chain 4: Iteration: 2000 / 2000 [100%]  (Sampling)
Chain 4: 
Chain 4:  Elapsed Time: 0.508 seconds (Warm-up)
Chain 4:                0.296 seconds (Sampling)
Chain 4:                0.804 seconds (Total)
Chain 4: 
 Family: gaussian 
  Links: mu = identity; sigma = identity 
Formula: PV1SCIE ~ PV1MATH + PV1READ 
   Data: UKPISA_2022 (Number of observations: 12972) 
  Draws: 4 chains, each with iter = 2000; warmup = 1000; thin = 1;
         total post-warmup draws = 4000

Regression Coefficients:
          Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
Intercept    25.65      2.21    21.38    29.93 1.00     5016     2785
PV1MATH       0.71      0.01     0.70     0.73 1.00     2277     2358
PV1READ       0.25      0.01     0.24     0.26 1.00     2277     2340

Further Distributional Parameters:
      Estimate Est.Error l-95% CI u-95% CI Rhat Bulk_ESS Tail_ESS
sigma    48.20      0.29    47.61    48.77 1.00     3373     2417

Draws were sampled using sampling(NUTS). For each parameter, Bulk_ESS
and Tail_ESS are effective sample size measures, and Rhat is the potential
scale reduction factor on split chains (at convergence, Rhat = 1).
    Estimate   Est.Error      Q2.5     Q97.5
R2 0.7774875 0.001610655 0.7743008 0.7805103</code></pre>
</div>
</div>
</section>
<section id="generating-multiple-models-and-comparing-them" class="level3" data-number="0.2.5">
<h3 data-number="0.2.5" class="anchored" data-anchor-id="generating-multiple-models-and-comparing-them"><span class="header-section-number">0.2.5</span> Generating multiple models and comparing them</h3>
<p>The <code>BayesFactor</code> package allows you to generate multiple models, based on different combinations of variables in a data set and compare their predictive power. Note that this approach is not recommended :</p>
<div class="callout callout-style-default callout-note callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Note
</div>
</div>
<div class="callout-body-container callout-body">
<p>“Let the computer find out” is a poor strategy and usually reflects the fact that the researcher didnot bother to think clearly about the problem of interest and its scientific setting <span class="citation" data-cites="burnham2007">(<a href="#ref-burnham2007" role="doc-biblioref">Burnham and Anderson 2007, 147</a>)</span></p>
</div>
</div>
<p>Nonetheless, once you have thought clearly about a range of models ranking the potential Bayesian models can provide insights. This can be done using the <code>regressionBF</code> function of the <code>BayesFactor</code> package. We call <code>models &lt;- regressionBF(PV1SCIE ~ ., data = PISAUK)</code> which asks for regression to predict science scores (<code>PV1SCIE~</code>) by all of the variables (<code>.</code>) in the data frame (<code>data=PISAUK</code>) Note that variables need to be converted to factor variables. The function returns a <code>data.frame</code> ranking the models, the one with the highest Bayes factor <code>bf</code> is a candidate for the best fit.</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-10"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><span id="annotated-cell-10-1"><a href="#annotated-cell-10-1"></a><span class="fu">library</span>(BayesFactor)</span>
<span id="annotated-cell-10-2"><a href="#annotated-cell-10-2"></a></span>
<span id="annotated-cell-10-3"><a href="#annotated-cell-10-3"></a><span class="co"># Create a UK subset                                                     </span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-10-4" class="code-annotation-target"><a href="#annotated-cell-10-4"></a>PISAUK <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-10-5"><a href="#annotated-cell-10-5"></a>  <span class="fu">select</span>(PV1MATH, PV1READ, PV1SCIE, HOMEPOS, ESCS, CNT) <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-10-6"><a href="#annotated-cell-10-6"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-10-7"><a href="#annotated-cell-10-7"></a>  <span class="fu">select</span>(<span class="sc">-</span>CNT) <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-10-8"><a href="#annotated-cell-10-8"></a>  <span class="fu">na.omit</span>()</span>
<span id="annotated-cell-10-9"><a href="#annotated-cell-10-9"></a></span>
<span id="annotated-cell-10-10"><a href="#annotated-cell-10-10"></a><span class="co"># Use regressionBF to create a dataframe of the models</span></span>
<span id="annotated-cell-10-11"><a href="#annotated-cell-10-11"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-10-12" class="code-annotation-target"><a href="#annotated-cell-10-12"></a>models <span class="ot">&lt;-</span> <span class="fu">regressionBF</span>(PV1SCIE <span class="sc">~</span> ., <span class="at">data =</span> PISAUK)</span>
<span id="annotated-cell-10-13"><a href="#annotated-cell-10-13"></a></span>
<span id="annotated-cell-10-14"><a href="#annotated-cell-10-14"></a><span class="co"># Select only the relevant part of the output</span></span>
<span id="annotated-cell-10-15"><a href="#annotated-cell-10-15"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-10-16" class="code-annotation-target"><a href="#annotated-cell-10-16"></a>output <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(models<span class="sc">@</span>bayesFactor)</span>
<span id="annotated-cell-10-17"><a href="#annotated-cell-10-17"></a></span>
<span id="annotated-cell-10-18"><a href="#annotated-cell-10-18"></a><span class="co"># Arrange the output</span></span>
<span id="annotated-cell-10-19"><a href="#annotated-cell-10-19"></a></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-10" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-10-20" class="code-annotation-target"><a href="#annotated-cell-10-20"></a>output <span class="ot">&lt;-</span> output <span class="sc">%&gt;%</span></span>
<span id="annotated-cell-10-21"><a href="#annotated-cell-10-21"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(bf))</span>
<span id="annotated-cell-10-22"><a href="#annotated-cell-10-22"></a>output</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-10" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-10" data-code-lines="4" data-code-annotation="1">line 1 create a subset of UK data, select reading, science, maths, wealth (<code>HOMEPOS</code>), class (<code>ESCS</code>) and country variables, filter for the UK then drop the unneeded <code>CNT</code> variable, then drop <code>NA</code>s</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-10" data-code-lines="12" data-code-annotation="2">The <code>regressionBF</code> function creates a data frame with all the possible linear models using the specified variables</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-10" data-code-lines="16" data-code-annotation="3">Select only the Bayes factor, and covert to a data frame for sort</span>
</dd>
<dt data-target-cell="annotated-cell-10" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-10" data-code-lines="20" data-code-annotation="4">Sort the output in descending order of Bayes Factor and print the output</span>
</dd>
</dl>
</div>
<div class="cell-output cell-output-stdout">
<pre><code>                                         bf        error
PV1MATH + PV1READ + HOMEPOS        8062.475 1.573489e-06
PV1MATH + PV1READ + HOMEPOS + ESCS 8061.225 1.088549e-04
PV1MATH + PV1READ + ESCS           8059.345 1.571910e-06
PV1MATH + PV1READ                  8036.480 3.141224e-06
PV1MATH + HOMEPOS                  7537.090 3.468842e-06
PV1MATH + HOMEPOS + ESCS           7534.309 1.336025e-06
PV1MATH + ESCS                     7525.691 3.476922e-06
PV1MATH                            7497.489 8.858089e-05
PV1READ + HOMEPOS + ESCS           5254.970 6.513346e-06
PV1READ + ESCS                     5242.466 3.000504e-06
                                                       time          code
PV1MATH + PV1READ + HOMEPOS        Tue Jun 11 10:50:42 2024 10247348382f4
PV1MATH + PV1READ + HOMEPOS + ESCS Tue Jun 11 10:50:42 2024 102473e50ca53
PV1MATH + PV1READ + ESCS           Tue Jun 11 10:50:42 2024 10247260a7c1b
PV1MATH + PV1READ                  Tue Jun 11 10:50:42 2024  10247cb8ffe2
PV1MATH + HOMEPOS                  Tue Jun 11 10:50:42 2024 1024745a754f4
PV1MATH + HOMEPOS + ESCS           Tue Jun 11 10:50:42 2024 102477a59e41f
PV1MATH + ESCS                     Tue Jun 11 10:50:42 2024 102476cba82e5
PV1MATH                            Tue Jun 11 10:50:42 2024  10247172e1bd
PV1READ + HOMEPOS + ESCS           Tue Jun 11 10:50:42 2024 10247238fedfa
PV1READ + ESCS                     Tue Jun 11 10:50:42 2024 1024766f865d5
 [ reached 'max' / getOption("max.print") -- omitted 5 rows ]</code></pre>
</div>
</div>
<p>We can compare the Bayes Factors of the models in a chart:</p>
<div class="cell">
<div class="sourceCode cell-code" id="annotated-cell-11"><pre class="sourceCode numberSource r code-annotation-code number-lines code-with-copy code-annotated"><code class="sourceCode r"><a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="1" onclick="event.preventDefault();">1</a><span id="annotated-cell-11-1" class="code-annotation-target"><a href="#annotated-cell-11-1"></a><span class="fu">ggplot</span>(output, <span class="fu">aes</span>(<span class="at">x =</span> <span class="fu">reorder</span>(<span class="fu">rownames</span>(output), <span class="sc">-</span>bf),</span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="2" onclick="event.preventDefault();">2</a><span id="annotated-cell-11-2" class="code-annotation-target"><a href="#annotated-cell-11-2"></a>                   <span class="at">y =</span> bf, <span class="at">fill =</span> <span class="fu">rownames</span>(output))) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="3" onclick="event.preventDefault();">3</a><span id="annotated-cell-11-3" class="code-annotation-target"><a href="#annotated-cell-11-3"></a>  <span class="fu">geom_col</span>() <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="4" onclick="event.preventDefault();">4</a><span id="annotated-cell-11-4" class="code-annotation-target"><a href="#annotated-cell-11-4"></a>  <span class="fu">theme</span>(<span class="at">axis.text.x =</span> <span class="fu">element_text</span>(<span class="at">angle =</span> <span class="dv">90</span>, <span class="at">vjust =</span> <span class="fl">0.5</span>, <span class="at">hjust=</span><span class="dv">1</span>)) <span class="sc">+</span></span>
<a class="code-annotation-anchor" data-target-cell="annotated-cell-11" data-target-annotation="5" onclick="event.preventDefault();">5</a><span id="annotated-cell-11-5" class="code-annotation-target"><a href="#annotated-cell-11-5"></a>  <span class="fu">labs</span>(<span class="at">x=</span><span class="st">"model"</span>, <span class="at">y=</span><span class="st">"Bayes Factor"</span>)</span><div class="code-annotation-gutter-bg"></div><div class="code-annotation-gutter"></div></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-annotation">
<dl class="code-annotation-container-grid">
<dt data-target-cell="annotated-cell-11" data-target-annotation="1">1</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="1" data-code-annotation="1">line 1 Use <code>ggplot</code> passing the <code>output</code> data frame to create graph. Within <code>aes</code> set the axis to the rownnames (i.e.&nbsp;the rank order of the models by Bayes Factor) and set to <code>reorder</code> in descending order <code>-bf</code> of the Bayes Factor</span>
</dd>
<dt data-target-cell="annotated-cell-11" data-target-annotation="2">2</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="2" data-code-annotation="2">line 2 Set the y-axis to the Bayes Factor, and set the fill to the rank index</span>
</dd>
<dt data-target-cell="annotated-cell-11" data-target-annotation="3">3</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="3" data-code-annotation="3">line 3 Plot a column graph</span>
</dd>
<dt data-target-cell="annotated-cell-11" data-target-annotation="4">4</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="4" data-code-annotation="4">line 4 Rotate the axis text</span>
</dd>
<dt data-target-cell="annotated-cell-11" data-target-annotation="5">5</dt>
<dd>
<span data-code-cell="annotated-cell-11" data-code-lines="5" data-code-annotation="5">line 5 Set the axis labels</span>
</dd>
</dl>
</div>
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="06-2-Bayesian_files/figure-html/unnamed-chunk-8-1.png" class="img-fluid figure-img" style="width:95.0%"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="tasks" class="level2" data-number="0.3">
<h2 data-number="0.3" class="anchored" data-anchor-id="tasks"><span class="header-section-number">0.3</span> Tasks</h2>
<section id="task-1-bayesian-chi-square" class="level3" data-number="0.3.1">
<h3 data-number="0.3.1" class="anchored" data-anchor-id="task-1-bayesian-chi-square"><span class="header-section-number">0.3.1</span> Task 1 Bayesian Chi Square</h3>
<div class="question">
<p>Use a Bayesian chi square test to determine: a) In the PISA 2022 data for the UK, determine if there are statistically significant differences for boys and girls for ST250Q01JA (“Which of the following are in your [home]: A room of your own” [Yes/No])</p>
<ol start="2" type="a">
<li>Determine if they are statistically significant differences in ST250Q02JA In your home: A computer (laptop, desktop, or tablet) that you can use for school work between the UK and the US</li>
</ol>
</div>
<div class="callout callout-style-default callout-tip callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Tip
</div>
</div>
<div class="callout-body-container callout-body">
<p>When analysing by country, after filtering for the countries of interest, it can be helpful to <code>drop_levels(&lt;dataframe&gt;)</code>. After filtering the other countries in the data frame will remain as levels, and will create a contingency table with many zero entries if not dropped. For example:</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb15"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb15-1"><a href="#cb15-1"></a><span class="co"># Create a data frame for having a computer in the UK and the US</span></span>
<span id="cb15-2"><a href="#cb15-2"></a>Comp <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb15-3"><a href="#cb15-3"></a>  <span class="fu">select</span>(CNT, ST250Q02JA) <span class="sc">%&gt;%</span></span>
<span id="cb15-4"><a href="#cb15-4"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span> <span class="sc">|</span> CNT <span class="sc">==</span> <span class="st">"United States"</span>) </span>
<span id="cb15-5"><a href="#cb15-5"></a></span>
<span id="cb15-6"><a href="#cb15-6"></a><span class="co"># Create a contingency table</span></span>
<span id="cb15-7"><a href="#cb15-7"></a>conttab <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="at">data =</span> Comp, <span class="sc">~</span> CNT <span class="sc">+</span> ST250Q02JA)</span>
<span id="cb15-8"><a href="#cb15-8"></a>conttab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                              ST250Q02JA
CNT                              Yes    No Valid Skip Not Applicable Invalid
  Albania                          0     0          0              0       0
  United Arab Emirates             0     0          0              0       0
  Argentina                        0     0          0              0       0
  Australia                        0     0          0              0       0
  Austria                          0     0          0              0       0
  Belgium                          0     0          0              0       0
                              ST250Q02JA
CNT                            No Response
  Albania                                0
  United Arab Emirates                   0
  Argentina                              0
  Australia                              0
  Austria                                0
  Belgium                                0
 [ reached getOption("max.print") -- omitted 75 rows ]</code></pre>
</div>
</div>
<p>Adding <code>drop_levels</code> solves this issues</p>
<div class="cell">
<div class="sourceCode cell-code" id="cb17"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb17-1"><a href="#cb17-1"></a><span class="co"># Create a data frame for having a computer to study at in the UK and the US</span></span>
<span id="cb17-2"><a href="#cb17-2"></a>Comp <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb17-3"><a href="#cb17-3"></a>  <span class="fu">select</span>(CNT, ST250Q02JA) <span class="sc">%&gt;%</span></span>
<span id="cb17-4"><a href="#cb17-4"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span><span class="sc">|</span> CNT <span class="sc">==</span> <span class="st">"United States"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb17-5"><a href="#cb17-5"></a>  <span class="fu">droplevels</span>() <span class="co"># Remove levels with 0 responses</span></span>
<span id="cb17-6"><a href="#cb17-6"></a></span>
<span id="cb17-7"><a href="#cb17-7"></a></span>
<span id="cb17-8"><a href="#cb17-8"></a><span class="co"># Create a contingency table</span></span>
<span id="cb17-9"><a href="#cb17-9"></a>conttab <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="at">data =</span> Comp, <span class="sc">~</span> CNT <span class="sc">+</span> ST250Q02JA)</span>
<span id="cb17-10"><a href="#cb17-10"></a>conttab</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
<div class="cell-output cell-output-stdout">
<pre><code>                ST250Q02JA
CNT                Yes    No
  United Kingdom 10634   703
  United States   4077   260</code></pre>
</div>
</div>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Answer A</summary>
<div class="sourceCode cell-code" id="cb19"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb19-1"><a href="#cb19-1"></a><span class="co"># Create a dataframe for having a room of their own the UK</span></span>
<span id="cb19-2"><a href="#cb19-2"></a>Room <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb19-3"><a href="#cb19-3"></a>  <span class="fu">select</span>(CNT, ST004D01T, ST250Q01JA) <span class="sc">%&gt;%</span></span>
<span id="cb19-4"><a href="#cb19-4"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb19-5"><a href="#cb19-5"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb19-6"><a href="#cb19-6"></a></span>
<span id="cb19-7"><a href="#cb19-7"></a><span class="co"># Create a contingency table</span></span>
<span id="cb19-8"><a href="#cb19-8"></a>conttab <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="at">data =</span> Room, <span class="sc">~</span> ST004D01T <span class="sc">+</span> ST250Q01JA)</span>
<span id="cb19-9"><a href="#cb19-9"></a></span>
<span id="cb19-10"><a href="#cb19-10"></a><span class="co"># Perform the Bayesian chi-square test</span></span>
<span id="cb19-11"><a href="#cb19-11"></a><span class="fu">contingencyTableBF</span>(conttab, <span class="at">sampleType =</span> <span class="st">"jointMulti"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>Bayes factor analysis
--------------
[1] Non-indep. (a=1) : 115.63 ±0%

Against denominator:
  Null, independence, a = 1 
---
Bayes factor type: BFcontingencyTable, joint multinomial</code></pre>
</div>
<details class="code-fold">
<summary>Answer A</summary>
<div class="sourceCode cell-code" id="cb21"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb21-1"><a href="#cb21-1"></a><span class="co"># Returns a base factor of 115 -   there is a 'decisive' difference by gender in having a computer</span></span>
<span id="cb21-2"><a href="#cb21-2"></a></span>
<span id="cb21-3"><a href="#cb21-3"></a><span class="co"># Compare to frequentist Chi squares test test</span></span>
<span id="cb21-4"><a href="#cb21-4"></a></span>
<span id="cb21-5"><a href="#cb21-5"></a><span class="fu">chisq.test</span>(conttab)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
<div class="cell-output cell-output-stdout">
<pre><code>
    Pearson's Chi-squared test with Yates' continuity correction

data:  conttab
X-squared = 17.041, df = 1, p-value = 3.658e-05</code></pre>
</div>
<details class="code-fold">
<summary>Answer A</summary>
<div class="sourceCode cell-code" id="cb23"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb23-1"><a href="#cb23-1"></a><span class="co"># p-value = 3.658e-05-06, less than 0.05 so there are different distributions by country</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Answer B</summary>
<div class="sourceCode cell-code" id="cb24"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1"></a><span class="co"># Create a data frame for having a computer in the UK and the US</span></span>
<span id="cb24-2"><a href="#cb24-2"></a><span class="co"># Drop levels of unneeded countries</span></span>
<span id="cb24-3"><a href="#cb24-3"></a></span>
<span id="cb24-4"><a href="#cb24-4"></a>Comp <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb24-5"><a href="#cb24-5"></a>  <span class="fu">select</span>(CNT, ST250Q02JA) <span class="sc">%&gt;%</span></span>
<span id="cb24-6"><a href="#cb24-6"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span> <span class="sc">|</span> CNT <span class="sc">==</span> <span class="st">"United States"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb24-7"><a href="#cb24-7"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb24-8"><a href="#cb24-8"></a></span>
<span id="cb24-9"><a href="#cb24-9"></a><span class="co"># Create a contingency table</span></span>
<span id="cb24-10"><a href="#cb24-10"></a>conttab <span class="ot">&lt;-</span> <span class="fu">xtabs</span>(<span class="at">data =</span> Comp, <span class="sc">~</span> CNT <span class="sc">+</span> ST250Q02JA)</span>
<span id="cb24-11"><a href="#cb24-11"></a></span>
<span id="cb24-12"><a href="#cb24-12"></a><span class="co"># Perform the Bayesian chi-square test</span></span>
<span id="cb24-13"><a href="#cb24-13"></a><span class="fu">contingencyTableBF</span>(conttab, <span class="at">sampleType =</span> <span class="st">"jointMulti"</span>)</span>
<span id="cb24-14"><a href="#cb24-14"></a></span>
<span id="cb24-15"><a href="#cb24-15"></a><span class="co"># Returns a base factor of 0.01439028 -  likely there are no differences between the UK and US</span></span>
<span id="cb24-16"><a href="#cb24-16"></a></span>
<span id="cb24-17"><a href="#cb24-17"></a><span class="co"># Compare to frequentist Chi squares test test</span></span>
<span id="cb24-18"><a href="#cb24-18"></a></span>
<span id="cb24-19"><a href="#cb24-19"></a><span class="fu">chisq.test</span>(conttab)</span>
<span id="cb24-20"><a href="#cb24-20"></a></span>
<span id="cb24-21"><a href="#cb24-21"></a><span class="co"># p-value = 0.6575, more than 0.05 so assume the null hypothesis of no difference in computer ownership between the US and UK</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="task-2-bayesian-t-tests" class="level3" data-number="0.3.2">
<h3 data-number="0.3.2" class="anchored" data-anchor-id="task-2-bayesian-t-tests"><span class="header-section-number">0.3.2</span> Task 2 Bayesian t-tests</h3>
<div class="question">
<p>Use a Bayesian t-test to determine: a) In the PISA 2022 data, are there statistically significant differences in reading scores (PV1READ) for boys and girls (look at <code>ST004D01T</code> for gender) in the UK? (You can check against a frequentist t-test if you like!)</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Answer</summary>
<div class="sourceCode cell-code" id="cb25"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1"></a><span class="co"># Create a data frame for having a Reading scores in the UK including gender</span></span>
<span id="cb25-2"><a href="#cb25-2"></a>Read <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb25-3"><a href="#cb25-3"></a>  <span class="fu">select</span>(CNT, ST004D01T, PV1READ) <span class="sc">%&gt;%</span></span>
<span id="cb25-4"><a href="#cb25-4"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb25-5"><a href="#cb25-5"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb25-6"><a href="#cb25-6"></a></span>
<span id="cb25-7"><a href="#cb25-7"></a><span class="co"># Perform the Bayesian test</span></span>
<span id="cb25-8"><a href="#cb25-8"></a><span class="fu">ttestBF</span>(<span class="at">data =</span> Read, <span class="at">formula =</span> PV1READ <span class="sc">~</span> ST004D01T)</span>
<span id="cb25-9"><a href="#cb25-9"></a></span>
<span id="cb25-10"><a href="#cb25-10"></a><span class="co"># The Bayes factor is 3.646098e+20 - it is highly likely that are differences between the genders in reading in the UK</span></span>
<span id="cb25-11"><a href="#cb25-11"></a></span>
<span id="cb25-12"><a href="#cb25-12"></a><span class="co"># Compare to frequentist test</span></span>
<span id="cb25-13"><a href="#cb25-13"></a></span>
<span id="cb25-14"><a href="#cb25-14"></a><span class="fu">t.test</span>(<span class="at">data =</span> Read, PV1READ <span class="sc">~</span> ST004D01T )</span>
<span id="cb25-15"><a href="#cb25-15"></a></span>
<span id="cb25-16"><a href="#cb25-16"></a><span class="co"># p-value &lt; 2.2e-16, less than 0.05 so there are differences in mean</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="question">
<p>Use a Bayesian t-test to determine: In the PISA 2020 data, are statistically significant differences in mathematics scores (<code>PV1MATH</code>) between the UK and the US?</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Answer</summary>
<div class="sourceCode cell-code" id="cb26"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb26-1"><a href="#cb26-1"></a><span class="co"># Create a data frame for having a mathematics scores in the UK and US </span></span>
<span id="cb26-2"><a href="#cb26-2"></a>PISAMath <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb26-3"><a href="#cb26-3"></a>  <span class="fu">select</span>(CNT, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb26-4"><a href="#cb26-4"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span><span class="sc">|</span> CNT <span class="sc">==</span> <span class="st">"United States"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb26-5"><a href="#cb26-5"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb26-6"><a href="#cb26-6"></a></span>
<span id="cb26-7"><a href="#cb26-7"></a></span>
<span id="cb26-8"><a href="#cb26-8"></a><span class="co"># Perform the Bayesian test</span></span>
<span id="cb26-9"><a href="#cb26-9"></a><span class="fu">ttestBF</span>(<span class="at">data =</span> PISAMath, <span class="at">formula =</span> PV1MATH <span class="sc">~</span> CNT)</span>
<span id="cb26-10"><a href="#cb26-10"></a></span>
<span id="cb26-11"><a href="#cb26-11"></a><span class="co"># The Bayes factor is 4.576009e+32 - it is highly likely that there is a difference in mean mathematics scores between the US and UK</span></span>
<span id="cb26-12"><a href="#cb26-12"></a></span>
<span id="cb26-13"><a href="#cb26-13"></a><span class="co"># Compare to frequentist test</span></span>
<span id="cb26-14"><a href="#cb26-14"></a></span>
<span id="cb26-15"><a href="#cb26-15"></a><span class="fu">t.test</span>(<span class="at">data =</span> PISAMath, PV1MATH <span class="sc">~</span> CNT)</span>
<span id="cb26-16"><a href="#cb26-16"></a></span>
<span id="cb26-17"><a href="#cb26-17"></a><span class="co"># p-value &lt; 2.2e-16, less than 0.05 so there are differences in mean</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="task-3-bayesian-linear-models" class="level3" data-number="0.3.3">
<h3 data-number="0.3.3" class="anchored" data-anchor-id="task-3-bayesian-linear-models"><span class="header-section-number">0.3.3</span> Task 3 Bayesian linear models</h3>
<div class="question">
<p>Use a Bayesian linear model to determine: a) In the PISA 2022 data, build a model of mathematics scores (<code>PV1MATH</code>) in the UK. What percentage of variance in mathematics score is explained by the model: <code>PV1MATH \~ PV1READ + ST004D01T (gender) + HOMEPOS</code></p>
</div>
<div class="callout callout-style-default callout-warning callout-titled">
<div class="callout-header d-flex align-content-center">
<div class="callout-icon-container">
<i class="callout-icon"></i>
</div>
<div class="callout-title-container flex-fill">
Warning
</div>
</div>
<div class="callout-body-container callout-body">
<p>A Bayesian linear model is processor intensive - this task might take a few minutes to run, depending on the speed of your machine. On my relatively new machine, the example below takes 52 seconds. On slower machines, you may want to make a cup of tea after you run it!</p>
</div>
</div>
<div class="cell">
<details class="code-fold">
<summary>Answer</summary>
<div class="sourceCode cell-code" id="cb27"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1"></a><span class="co"># Create a data frame for having a Reading scores in the UK including gender</span></span>
<span id="cb27-2"><a href="#cb27-2"></a>UKMath <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb27-3"><a href="#cb27-3"></a>  <span class="fu">select</span>(CNT, ST004D01T, PV1MATH, HOMEPOS, PV1READ) <span class="sc">%&gt;%</span></span>
<span id="cb27-4"><a href="#cb27-4"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb27-5"><a href="#cb27-5"></a>  <span class="fu">droplevels</span>()</span>
<span id="cb27-6"><a href="#cb27-6"></a></span>
<span id="cb27-7"><a href="#cb27-7"></a><span class="co"># Perform the Bayesian linear model</span></span>
<span id="cb27-8"><a href="#cb27-8"></a>mod <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data=</span>UKMath, PV1MATH <span class="sc">~</span> PV1READ <span class="sc">+</span> ST004D01T <span class="sc">+</span> HOMEPOS)</span>
<span id="cb27-9"><a href="#cb27-9"></a><span class="fu">summary</span>(mod)</span>
<span id="cb27-10"><a href="#cb27-10"></a></span>
<span id="cb27-11"><a href="#cb27-11"></a><span class="co"># Calculate the Bayesian equivalent of R2</span></span>
<span id="cb27-12"><a href="#cb27-12"></a><span class="fu">bayes_R2</span>(mod)</span>
<span id="cb27-13"><a href="#cb27-13"></a></span>
<span id="cb27-14"><a href="#cb27-14"></a><span class="co"># The model explains 64% of the variance</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="question">
<p>Use a Bayesian linear model to build the best model you can of the difference between boys and girls mathematics scores in the whole day set. a) Create a data frame of boys and girls mathematics achievement across the world using <code>summarise</code> b) Use <code>mutate</code> to a difference in score column c) Propose a model (consider e.g., <code>PV1READ</code>, <code>WEALTH</code> etc), calculate the R2 value, and then tune the model by adding additional independent variable to increase its R2</p>
<p>If you aren’t feeling confident with your R data manipulation, you can use the hint below to start with a data frame of gender difference and various variables by country.</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Hint</summary>
<div class="sourceCode cell-code" id="cb28"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb28-1"><a href="#cb28-1"></a><span class="co"># Creating the data frame for analysis</span></span>
<span id="cb28-2"><a href="#cb28-2"></a><span class="co"># Create a data frame for having a mathematics scores by  gender</span></span>
<span id="cb28-3"><a href="#cb28-3"></a>MathScore <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb28-4"><a href="#cb28-4"></a>  <span class="fu">select</span>(CNT, ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb28-5"><a href="#cb28-5"></a>  <span class="fu">group_by</span>(CNT, ST004D01T) <span class="sc">%&gt;%</span></span>
<span id="cb28-6"><a href="#cb28-6"></a>  <span class="fu">summarise</span>(<span class="at">math=</span><span class="fu">mean</span>(PV1MATH)) <span class="sc">%&gt;%</span></span>
<span id="cb28-7"><a href="#cb28-7"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb28-8"><a href="#cb28-8"></a></span>
<span id="cb28-9"><a href="#cb28-9"></a><span class="co"># Use pviot_wider to create side-by-sde columns for mathematics score</span></span>
<span id="cb28-10"><a href="#cb28-10"></a></span>
<span id="cb28-11"><a href="#cb28-11"></a>MathScore <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(<span class="at">data=</span>MathScore, <span class="at">names_from=</span>ST004D01T, <span class="at">values_from=</span>math)</span>
<span id="cb28-12"><a href="#cb28-12"></a></span>
<span id="cb28-13"><a href="#cb28-13"></a>MathScore <span class="ot">&lt;-</span> MathScore <span class="sc">%&gt;%</span></span>
<span id="cb28-14"><a href="#cb28-14"></a>  <span class="fu">mutate</span>(<span class="at">genddiff =</span> Female <span class="sc">-</span> Male)</span>
<span id="cb28-15"><a href="#cb28-15"></a></span>
<span id="cb28-16"><a href="#cb28-16"></a><span class="co"># Create a summary of means of the indepedent variables (e.g. WEALTH, reading etc) by country</span></span>
<span id="cb28-17"><a href="#cb28-17"></a>Independents <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb28-18"><a href="#cb28-18"></a>  <span class="fu">select</span>(CNT, PV1READ, WEALTH, ESCS) <span class="sc">%&gt;%</span></span>
<span id="cb28-19"><a href="#cb28-19"></a>  <span class="fu">group_by</span>(CNT) <span class="sc">%&gt;%</span></span>
<span id="cb28-20"><a href="#cb28-20"></a>  <span class="fu">summarise</span>(<span class="at">read=</span><span class="fu">mean</span>(PV1READ, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb28-21"><a href="#cb28-21"></a>            <span class="at">wealth=</span><span class="fu">mean</span>(WEALTH, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb28-22"><a href="#cb28-22"></a>            <span class="at">ESCS=</span><span class="fu">mean</span>(ESCS, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb28-23"><a href="#cb28-23"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb28-24"><a href="#cb28-24"></a></span>
<span id="cb28-25"><a href="#cb28-25"></a><span class="co"># join the independents to the maths scores gender differences</span></span>
<span id="cb28-26"><a href="#cb28-26"></a>MathScore <span class="ot">&lt;-</span> <span class="fu">left_join</span>(MathScore, Independents, <span class="at">by=</span><span class="st">"CNT"</span>)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
<div class="cell">
<details class="code-fold">
<summary>Full Answer</summary>
<div class="sourceCode cell-code" id="cb29"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1"></a><span class="co"># Create a data frame for having a mathematics scores by  gender</span></span>
<span id="cb29-2"><a href="#cb29-2"></a>MathScore <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb29-3"><a href="#cb29-3"></a>  <span class="fu">select</span>(CNT, ST004D01T, PV1MATH) <span class="sc">%&gt;%</span></span>
<span id="cb29-4"><a href="#cb29-4"></a>  <span class="fu">group_by</span>(CNT, ST004D01T) <span class="sc">%&gt;%</span></span>
<span id="cb29-5"><a href="#cb29-5"></a>  <span class="fu">summarise</span>(<span class="at">math=</span><span class="fu">mean</span>(PV1MATH)) <span class="sc">%&gt;%</span></span>
<span id="cb29-6"><a href="#cb29-6"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb29-7"><a href="#cb29-7"></a></span>
<span id="cb29-8"><a href="#cb29-8"></a><span class="co"># Use pviot_wider to create side-by-sde columns for mathematics score</span></span>
<span id="cb29-9"><a href="#cb29-9"></a></span>
<span id="cb29-10"><a href="#cb29-10"></a>MathScore <span class="ot">&lt;-</span> <span class="fu">pivot_wider</span>(<span class="at">data=</span>MathScore, <span class="at">names_from=</span>ST004D01T, <span class="at">values_from=</span>math)</span>
<span id="cb29-11"><a href="#cb29-11"></a>MathScore <span class="ot">&lt;-</span> MathScore <span class="sc">%&gt;%</span></span>
<span id="cb29-12"><a href="#cb29-12"></a>  <span class="fu">mutate</span>(<span class="at">genddiff =</span> Female <span class="sc">-</span> Male)</span>
<span id="cb29-13"><a href="#cb29-13"></a></span>
<span id="cb29-14"><a href="#cb29-14"></a><span class="co"># Create a summary of means of the independent variables (e.g. WEALTH, reading etc) by country</span></span>
<span id="cb29-15"><a href="#cb29-15"></a></span>
<span id="cb29-16"><a href="#cb29-16"></a>Independents <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb29-17"><a href="#cb29-17"></a>  <span class="fu">select</span>(CNT, PV1READ, HOMEPOS, ESCS) <span class="sc">%&gt;%</span></span>
<span id="cb29-18"><a href="#cb29-18"></a>  <span class="fu">group_by</span>(CNT) <span class="sc">%&gt;%</span></span>
<span id="cb29-19"><a href="#cb29-19"></a>  <span class="fu">summarise</span>(<span class="at">read   =</span> <span class="fu">mean</span>(PV1READ, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb29-20"><a href="#cb29-20"></a>            <span class="at">wealth =</span> <span class="fu">mean</span>(HOMEPOS, <span class="at">na.rm=</span><span class="cn">TRUE</span>),</span>
<span id="cb29-21"><a href="#cb29-21"></a>            <span class="at">ESCS   =</span> <span class="fu">mean</span>(ESCS, <span class="at">na.rm=</span><span class="cn">TRUE</span>)) <span class="sc">%&gt;%</span></span>
<span id="cb29-22"><a href="#cb29-22"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb29-23"><a href="#cb29-23"></a><span class="co"># join the independents to the maths scores gender differences</span></span>
<span id="cb29-24"><a href="#cb29-24"></a></span>
<span id="cb29-25"><a href="#cb29-25"></a>MathScore <span class="ot">&lt;-</span> <span class="fu">left_join</span>(MathScore, Independents, <span class="at">by=</span><span class="st">"CNT"</span>)</span>
<span id="cb29-26"><a href="#cb29-26"></a></span>
<span id="cb29-27"><a href="#cb29-27"></a><span class="co"># Perform the Bayesian linear model with reading alone</span></span>
<span id="cb29-28"><a href="#cb29-28"></a>mod <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data =</span> MathScore, genddiff <span class="sc">~</span> read)</span>
<span id="cb29-29"><a href="#cb29-29"></a><span class="fu">summary</span>(mod)</span>
<span id="cb29-30"><a href="#cb29-30"></a><span class="co"># Calculate the Bayesian equivalent of R2</span></span>
<span id="cb29-31"><a href="#cb29-31"></a><span class="fu">bayes_R2</span>(mod)</span>
<span id="cb29-32"><a href="#cb29-32"></a><span class="co"># The reading only model explains 8% of the variance</span></span>
<span id="cb29-33"><a href="#cb29-33"></a></span>
<span id="cb29-34"><a href="#cb29-34"></a><span class="co"># Perform the Bayesian linear model with reading and wealth</span></span>
<span id="cb29-35"><a href="#cb29-35"></a>mod <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data=</span>MathScore, genddiff <span class="sc">~</span> read <span class="sc">+</span> wealth)</span>
<span id="cb29-36"><a href="#cb29-36"></a><span class="fu">summary</span>(mod)</span>
<span id="cb29-37"><a href="#cb29-37"></a></span>
<span id="cb29-38"><a href="#cb29-38"></a><span class="co"># Calculate the Bayesian equivalent of R2</span></span>
<span id="cb29-39"><a href="#cb29-39"></a><span class="fu">bayes_R2</span>(mod)</span>
<span id="cb29-40"><a href="#cb29-40"></a></span>
<span id="cb29-41"><a href="#cb29-41"></a><span class="co"># The reading and wealth model explains 19% of the variance</span></span>
<span id="cb29-42"><a href="#cb29-42"></a></span>
<span id="cb29-43"><a href="#cb29-43"></a><span class="co"># Perform the Bayesian linear model with reading, wealth and ESCS</span></span>
<span id="cb29-44"><a href="#cb29-44"></a>mod <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data=</span>MathScore, genddiff <span class="sc">~</span> read <span class="sc">+</span> wealth <span class="sc">+</span> ESCS)</span>
<span id="cb29-45"><a href="#cb29-45"></a><span class="fu">summary</span>(mod)</span>
<span id="cb29-46"><a href="#cb29-46"></a></span>
<span id="cb29-47"><a href="#cb29-47"></a><span class="co"># Calculate the Bayesian equivalent of R2</span></span>
<span id="cb29-48"><a href="#cb29-48"></a><span class="fu">bayes_R2</span>(mod)</span>
<span id="cb29-49"><a href="#cb29-49"></a></span>
<span id="cb29-50"><a href="#cb29-50"></a><span class="co"># The reading, wealth and ESCS model explains 20% of the variance</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="task-4-bayesian-linear-models" class="level3" data-number="0.3.4">
<h3 data-number="0.3.4" class="anchored" data-anchor-id="task-4-bayesian-linear-models"><span class="header-section-number">0.3.4</span> Task 4 Bayesian linear models</h3>
<div class="question">
<p>Use a Bayesian linear model to determine: a) In the UK PISA 2022 data, build a model of mathematics scores (<code>PV1MATH</code>) in the US based on reading scores (<code>PV1READ</code>) and science scores (<code>PV1SCIE</code>). Using the 2018 dataset to provide prior distributions for reading and science scores. Plot the distribution of the model parameters.</p>
<p>To use as prior data, you can download the PISA 2018 data <a href="https://emckclac-my.sharepoint.com/:u:/g/personal/k1926273_kcl_ac_uk/EdW6FgViBOBLsPWA7-OeF5AB55X76IcOBxWOCS_LqsyRXw?e=dV2k8m">here</a>.</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Answer</summary>
<div class="sourceCode cell-code" id="cb30"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb30-1"><a href="#cb30-1"></a><span class="co"># Determine prior distribution parameters</span></span>
<span id="cb30-2"><a href="#cb30-2"></a></span>
<span id="cb30-3"><a href="#cb30-3"></a>scie_summary <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb30-4"><a href="#cb30-4"></a>  <span class="fu">select</span>(PV1SCIE, CNT) <span class="sc">%&gt;%</span></span>
<span id="cb30-5"><a href="#cb30-5"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-6"><a href="#cb30-6"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(PV1SCIE, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb30-7"><a href="#cb30-7"></a>            <span class="at">sd=</span><span class="fu">sd</span>(PV1SCIE, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb30-8"><a href="#cb30-8"></a></span>
<span id="cb30-9"><a href="#cb30-9"></a>scie_mean <span class="ot">&lt;-</span> scie_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(mean)</span>
<span id="cb30-10"><a href="#cb30-10"></a>scie_sd   <span class="ot">&lt;-</span> scie_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(sd)</span>
<span id="cb30-11"><a href="#cb30-11"></a></span>
<span id="cb30-12"><a href="#cb30-12"></a>read_summary <span class="ot">&lt;-</span> PISA_2018 <span class="sc">%&gt;%</span></span>
<span id="cb30-13"><a href="#cb30-13"></a>  <span class="fu">select</span>(PV1READ,CNT) <span class="sc">%&gt;%</span></span>
<span id="cb30-14"><a href="#cb30-14"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>) <span class="sc">%&gt;%</span></span>
<span id="cb30-15"><a href="#cb30-15"></a>  <span class="fu">summarise</span>(<span class="at">mean=</span><span class="fu">mean</span>(PV1READ, <span class="at">na.rm=</span><span class="cn">TRUE</span>), </span>
<span id="cb30-16"><a href="#cb30-16"></a>            <span class="at">sd=</span><span class="fu">sd</span>(PV1READ, <span class="at">na.rm=</span><span class="cn">TRUE</span>))</span>
<span id="cb30-17"><a href="#cb30-17"></a></span>
<span id="cb30-18"><a href="#cb30-18"></a>read_mean <span class="ot">&lt;-</span> read_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(mean)</span>
<span id="cb30-19"><a href="#cb30-19"></a>read_sd   <span class="ot">&lt;-</span> read_summary <span class="sc">%&gt;%</span> <span class="fu">pull</span>(sd)</span>
<span id="cb30-20"><a href="#cb30-20"></a></span>
<span id="cb30-21"><a href="#cb30-21"></a><span class="co"># Specify the prior distribution using set priors from the `BMS` package</span></span>
<span id="cb30-22"><a href="#cb30-22"></a>prior2018 <span class="ot">&lt;-</span> <span class="fu">c</span>(<span class="fu">set_prior</span>(<span class="fu">glue</span>(<span class="st">"normal({scie_mean},{scie_sd})"</span>), <span class="at">class =</span> <span class="st">"b"</span>, <span class="at">coef =</span> <span class="st">"PV1SCIE"</span>),</span>
<span id="cb30-23"><a href="#cb30-23"></a>               <span class="fu">set_prior</span>(<span class="fu">glue</span>(<span class="st">"normal({read_mean},{read_sd})"</span>), <span class="at">class =</span> <span class="st">"b"</span>, <span class="at">coef =</span> <span class="st">"PV1READ"</span>))</span>
<span id="cb30-24"><a href="#cb30-24"></a></span>
<span id="cb30-25"><a href="#cb30-25"></a><span class="co"># Create the data frame of UK scores in 2018 to model</span></span>
<span id="cb30-26"><a href="#cb30-26"></a>UKPISA_2022 <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb30-27"><a href="#cb30-27"></a>  <span class="fu">filter</span>(CNT<span class="sc">==</span><span class="st">"United Kingdom"</span>)</span>
<span id="cb30-28"><a href="#cb30-28"></a></span>
<span id="cb30-29"><a href="#cb30-29"></a><span class="co"># Use the Bayesian regression model function 'brm' to fir the model, specifying the prior</span></span>
<span id="cb30-30"><a href="#cb30-30"></a>modbay <span class="ot">&lt;-</span> <span class="fu">brm</span>(<span class="at">data=</span>UKPISA_2022, <span class="at">formula =</span> PV1MATH <span class="sc">~</span> PV1SCIE <span class="sc">+</span> PV1READ, <span class="at">prior=</span>prior2018)</span>
<span id="cb30-31"><a href="#cb30-31"></a><span class="fu">summary</span>(modbay)</span>
<span id="cb30-32"><a href="#cb30-32"></a><span class="fu">bayes_R2</span>(modbay)</span>
<span id="cb30-33"><a href="#cb30-33"></a></span>
<span id="cb30-34"><a href="#cb30-34"></a><span class="co"># Plot the distribution of the coefficients</span></span>
<span id="cb30-35"><a href="#cb30-35"></a><span class="fu">plot</span>(modbay)</span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
<section id="task-5-bayesian-comparison-of-models" class="level3" data-number="0.3.5">
<h3 data-number="0.3.5" class="anchored" data-anchor-id="task-5-bayesian-comparison-of-models"><span class="header-section-number">0.3.5</span> Task 5 Bayesian comparison of models</h3>
<div class="question">
<p>Use the <code>regressionBF</code> function of the <code>BayesFactor</code> package to compare different models for the performance of UK students in mathematics. What is the best model you can find?</p>
</div>
<div class="cell">
<details class="code-fold">
<summary>Answer</summary>
<div class="sourceCode cell-code" id="cb31"><pre class="sourceCode numberSource r number-lines code-with-copy"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1"></a><span class="co"># Create a UK subset</span></span>
<span id="cb31-2"><a href="#cb31-2"></a>PISAUK <span class="ot">&lt;-</span> PISA_2022 <span class="sc">%&gt;%</span></span>
<span id="cb31-3"><a href="#cb31-3"></a>  <span class="fu">select</span>(PV1MATH, PV1READ, PV1SCIE, HOMEPOS, ESCS, CNT) <span class="sc">%&gt;%</span></span>
<span id="cb31-4"><a href="#cb31-4"></a>  <span class="fu">filter</span>(CNT <span class="sc">==</span> <span class="st">"United Kingdom"</span>)<span class="sc">%&gt;%</span></span>
<span id="cb31-5"><a href="#cb31-5"></a>  <span class="fu">select</span>(<span class="sc">-</span>CNT) <span class="sc">%&gt;%</span></span>
<span id="cb31-6"><a href="#cb31-6"></a>  <span class="fu">na.omit</span>()</span>
<span id="cb31-7"><a href="#cb31-7"></a></span>
<span id="cb31-8"><a href="#cb31-8"></a><span class="co"># Convert variables to numeric</span></span>
<span id="cb31-9"><a href="#cb31-9"></a>PISAUK<span class="sc">$</span>HOMEPOS <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(PISAUK<span class="sc">$</span>HOMEPOS)</span>
<span id="cb31-10"><a href="#cb31-10"></a>PISAUK<span class="sc">$</span>PV1SCIE <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(PISAUK<span class="sc">$</span>PV1SCIE)</span>
<span id="cb31-11"><a href="#cb31-11"></a>PISAUK<span class="sc">$</span>PV1READ <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(PISAUK<span class="sc">$</span>PV1READ)</span>
<span id="cb31-12"><a href="#cb31-12"></a>PISAUK<span class="sc">$</span>PV1MATH <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(PISAUK<span class="sc">$</span>PV1MATH)</span>
<span id="cb31-13"><a href="#cb31-13"></a>PISAUK<span class="sc">$</span>ESCS    <span class="ot">&lt;-</span> <span class="fu">as.numeric</span>(PISAUK<span class="sc">$</span>ESCS)</span>
<span id="cb31-14"><a href="#cb31-14"></a></span>
<span id="cb31-15"><a href="#cb31-15"></a><span class="co"># Use regressionBF to create a dataframe of the models</span></span>
<span id="cb31-16"><a href="#cb31-16"></a>models <span class="ot">&lt;-</span> <span class="fu">regressionBF</span>(PV1MATH <span class="sc">~</span> ., <span class="at">data =</span> PISAUK)</span>
<span id="cb31-17"><a href="#cb31-17"></a></span>
<span id="cb31-18"><a href="#cb31-18"></a><span class="co"># Select only the relevant part of the output</span></span>
<span id="cb31-19"><a href="#cb31-19"></a>output <span class="ot">&lt;-</span> <span class="fu">as.data.frame</span>(models<span class="sc">@</span>bayesFactor)</span>
<span id="cb31-20"><a href="#cb31-20"></a></span>
<span id="cb31-21"><a href="#cb31-21"></a><span class="co"># Arrange the output</span></span>
<span id="cb31-22"><a href="#cb31-22"></a>output<span class="ot">&lt;-</span>output<span class="sc">%&gt;%</span></span>
<span id="cb31-23"><a href="#cb31-23"></a>  <span class="fu">arrange</span>(<span class="fu">desc</span>(output<span class="sc">$</span>bf))</span>
<span id="cb31-24"><a href="#cb31-24"></a>output</span>
<span id="cb31-25"><a href="#cb31-25"></a><span class="co"># The best model appears to be: PV1SCIE ~ PV1READ + PV1SCIE + ESCS</span></span></code><button title="Copy to Clipboard" class="code-copy-button"><i class="bi"></i></button></pre></div>
</details>
</div>
</section>
</section>
<section id="further-reading" class="level2" data-number="0.4">
<h2 data-number="0.4" class="anchored" data-anchor-id="further-reading"><span class="header-section-number">0.4</span> Further reading</h2>
<p>You can find a nice introduction to Bayesian approaches in Michael Clark’s <a href="https://m-clark.github.io/bayesian-basics/"><em>Bayesian Basics</em></a>. For further reading, there are a number of <a href="https://bookdown.org/home/tags/bayesian/">Bookdown texts</a> on more advanced topics in using Bayesian packages in R.</p>



</section>

<div id="quarto-appendix" class="default"><section class="quarto-appendix-contents" role="doc-bibliography" id="quarto-bibliography"><h2 class="anchored quarto-appendix-heading">References</h2><div id="refs" class="references csl-bib-body hanging-indent" data-entry-spacing="0" role="list">
<div id="ref-burnham2007" class="csl-entry" role="listitem">
Burnham, Kenneth P., and David R. Anderson. 2007. <em>Model Selection and Multimodel Inference: A Practical Information-Theoretic Approach</em>. Springer Science &amp; Business Media.
</div>
<div id="ref-edwards1963" class="csl-entry" role="listitem">
Edwards, Ward, Harold Lindman, and Leonard J. Savage. 1963. <span>“Bayesian Statistical Inference for Psychological Research.”</span> <em>Psychological Review</em> 70 (3): 193–242. <a href="https://doi.org/10.1037/h0044139">https://doi.org/10.1037/h0044139</a>.
</div>
<div id="ref-kass1995" class="csl-entry" role="listitem">
Kass, Robert E., and Adrian E. Raftery. 1995. <span>“Bayes Factors.”</span> <em>Journal of the American Statistical Association</em> 90 (430): 773–95. <a href="https://doi.org/10.1080/01621459.1995.10476572">https://doi.org/10.1080/01621459.1995.10476572</a>.
</div>
<div id="ref-murphy1990if" class="csl-entry" role="listitem">
Murphy, Kevin R. 1990. <span>“If the Null Hypothesis Is Impossible, Why Test It?”</span> <em>American Psychologist</em> 45 (3): 403.
</div>
</div></section></div></main> <!-- /main -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>